<font color=red>**Danger zone:**</font> you'll be fine-tuning a model to generate positive, negative or even toxic reviews. We'll be doing this for fun, but this is also the technique for [review bombing](https://en.wikipedia.org/wiki/Review_bomb), bot farms on social media and other less than dignified stuff. It is ultimately your decision how you apply this knowledge, but before you choose, ask yourself: is this why you chose to learn ML?


# LLMs Alignment with Reinforcement Learning from human feedback (RLHF).

_based on the [original notebook](https://github.com/antndlcrx/oxford-llms-workshop/blob/main/materials/seminars/day_3/8_LLMs%20alignment%20with%20RLHF.ipynb) by Ilya Boytsov for the Oxford LLMs workshop_

In this session, you're gonna fine-tune a language model with reinforcement learning to make it generate good (or bad) reviews.

To perform RL-based fine-tuning, we'll use a new (in this course) library called [Transformer Reinforcement Learning (TRL)](https://huggingface.co/docs/trl). TRL implements the main reinforcement learning components of RLHF: reward modeling and fine-tuning with PPO.

![img](https://huggingface.co/datasets/trl-internal-testing/example-images/resolve/main/images/TRL-readme.png)

In [ ]:
%pip install -q trl==0.11.0 transformers==4.45.2 datasets==3.4.1 peft==0.14.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.4/316.4 kB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 54.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 22.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 68.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.2/181.2 kB 17.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.

### Tutorial: align the model to generate positive movie reviews

To see how TRL works, we'll use it to align GPT2 on IMDB dataset to generate positive (or negative) movie reviews. In fact, __it's your choice whether you want positive or negative reviews.__

But before you choose, let's take a look at the baseline model: a GPT-2 fine-tuned on generating arbitrary movie reviews.

In [ ]:
import torch
import transformers
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
main_tokenizer = transformers.AutoTokenizer.from_pretrained("lvwerra/gpt2-imdb")
main_model = transformers.AutoModelForCausalLM.from_pretrained("lvwerra/gpt2-imdb", device_map=device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/17.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/577 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/548M [00:00<?, ?B/s]

In [ ]:
inputs = main_tokenizer("The movie", return_tensors='pt').to(device)
generated_ids = main_model.generate(**inputs, max_new_tokens=50, do_sample=True)
print("\nGenerated text:", main_tokenizer.decode(generated_ids.flatten().cpu().numpy().tolist()))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Generated text: The movie could have saved its time by being less predictable, but not.<br /><br />In my view, most directors would have liked to use a somewhat more sophisticated approach to the plot. One thing that I liked about the movie was that most of

If you run this cell a couple of times, you'll see that the model generates both positive, negative and neutral reviews in some proportion. What we're gonna do next is teach the model to generate more positive (or negative) reviews.

Similarly to InstructGPT, we're gonna do that in 2 stages:
- **train a reward model** to assign higher values to positive (or negative) reviews
- fine-tune the language model to **maximize that reward using [proximal policy optimization](https://openai.com/research/openai-baselines-ppo)**

## Stage 1: train a reward model

First, we'll train a BERT-like model as our reward model. We'll generate a synthetic pairwise rankings to emulate human rankings.

__Q:__ why do I need a reward model? Can I just use a pre-trained sentiment classifier? <br> __A:__ Yes, you can - but that only works for movie reviews. But this tutorial will teach you how to do RLHF for any kind objective.


__If you actually want to maximize sentiment (or other "label") instead of human preferences, train reward model as a classifier! (see week5)__

In [ ]:
# We'll be fine-tuning a small BERT-like model for now. Please try other models for the main assignment.
reward_model = transformers.AutoModelForSequenceClassification.from_pretrained("distilbert-base-cased", device_map=device)
reward_tokenizer = transformers.AutoTokenizer.from_pretrained("distilbert-base-cased")

config.json:   0%|          | 0.00/465 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/263M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

__Note that__ the reward model has a separate tokenizer, different from the main model. They don't need to be the same for RLHF fine-tuning.

In [ ]:
# To train a reward model, you need a dataset (or generator) of positive-negative pairs.
# Each training sample should be a dict with 4 keys:
#  - input_ids_chosen, attention_mask_chosen = tokenizer("A sentence that human labeler likes more")
#  - input_ids_rejected, attention_mask_rejected = tokenizer("A sentence that human labeler likes less")

import torch
import datasets

class IMDBPairwiseDataset(torch.utils.data.Dataset):
    """ A dataset of all possible pairs of chosen and texts in TRT reward training format """
    def __init__(self, imdb, tokenizer, accepted_label: int):
        super().__init__()
        self.tokenizer = tokenizer
        self.chosen_texts = [row['text'] for row in imdb if row['label'] == accepted_label]
        self.rejected_texts = [row['text'] for row in imdb if row['label'] != accepted_label]
        self.column_names = ['input_ids_chosen', 'attention_mask_chosen', 'input_ids_rejected', 'attention_mask_rejected']
        assert self.chosen_texts, f"no texts with label {accepted_label}"
        print(f"Found {len(self.chosen_texts)} chosen and {len(self.rejected_texts)} rejected texts, {len(self)} pairs")

    def __len__(self):
        return len(self.chosen_texts) * len(self.rejected_texts)  # all pairs

    def __getitem__(self, index: int):
        chosen = self.tokenizer(self.chosen_texts[index // len(self.chosen_texts)], truncation=True)
        rejected = self.tokenizer(self.rejected_texts[index % len(self.chosen_texts)], truncation=True)
        return dict(input_ids_chosen=chosen['input_ids'], attention_mask_chosen=chosen['attention_mask'],
                    input_ids_rejected=rejected['input_ids'], attention_mask_rejected=rejected['attention_mask'])

In [ ]:
TARGET_LABEL = 0  # and make sure it works by reviewing the sample printed below
imdb = datasets.load_dataset("imdb", split='train')
reward_data = IMDBPairwiseDataset(imdb, reward_tokenizer, accepted_label=TARGET_LABEL)

sample = reward_data[31337]
print('CHOSEN:', reward_tokenizer.decode(sample['input_ids_chosen']))
print('REJECTED:', reward_tokenizer.decode(sample['input_ids_rejected']))

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Found 12500 chosen and 12500 rejected texts, 156250000 pairs
CHOSEN: [CLS] If only to avoid making this type of film in the future. This film is interesting as an experiment but tells no cogent story. < br / > < br / > One might feel virtuous for sitting thru it because it touches on so many IMPORTANT issues but it does so without any discernable motive. The viewer comes away with no new perspectives ( unless one comes up with one while one ' s mind wanders, as it will invariably do during this pointless film ). < br / > < br / > One might better spend one ' s time staring out a window at a tree growing. < br / > < br / > [SEP]
REJECTED: [CLS] This movie has some things that are pretty amazing. First, it is supposed to be based on a true story. That, in itself, is amazing that multiple tornadoes would hit the same town at night in the fall - in Nebraska. I wonder if the real town ' s name was close to " Blainsworth " ( which is the town ' s name in the movie ). There is an Ainsworth, Nebraska, but there is also a town that starts with Blains - something. < br / > < br / > It does show the slowest moving tornadoes on record in the the seen where the boys are in the house. On the other hand, the scene where the TV goes fuzzy is based in fact. Before Doppler radar and weather radio, we were taught that if you turned your TV to a particular channel ( not on cable ) and tuned the brightness just right, you could tell if there was a tornado coming. The problem was that by then you would be able to hear it. < br / > < br / > Since I know something about midwest tornadoes, it made this movie fun for me. I enjoy it more than Twister. I mean, give me a break - there is no way you could make it through and F5 by chaining yourself to a pipe in a well house. [SEP]

We'll be using `trl.RewardTrainer` - a special case of `transformers.Trainer` that you used in the past. `RewardTrainer` accepts the same format of training arguments (e.g. batch size, gradient checkpointing) as before, except that it trains the model for the pairwise reward objective from [the InstructGPT paper](https://arxiv.org/pdf/2203.02155.pdf):

![img](https://i.imgur.com/2JzNAPs.png)

Note that the model itself does not score pairs: it processes chosen ($y_w$) and rejected ($y_l$) samples independently. To minimize this loss, the reward model needs to score chosen sample higher than the rejected one. Note that the formula also assumes some context $x$, which is useful for seq2seq tasks. In our case of movie reviews, $x$ is empty.

In [ ]:
import trl
import os


training_args = trl.RewardConfig(  # like transformers.TrainingArguments
    output_dir="reward_model",
    per_device_train_batch_size=32,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-5,
    max_steps=1_000,              # note: training may need more than 1k steps
    logging_steps=50,
    gradient_checkpointing=True,  # reduce memory usage but train ~30% slower
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=True,                     # disable this on CPU or on very old GPUs
    # you may add any other hyperparameters that you found useful in weeks 5-7
    report_to="none",
)

trainer = trl.RewardTrainer(
    model=reward_model,
    args=training_args,
    tokenizer=reward_tokenizer,
    train_dataset=reward_data,
    peft_config=None,  # optionally, you may tune with LoRA, prompt-tuning, etc
)


trainer.train()

/usr/local/lib/python3.12/dist-packages/trl/trainer/reward_trainer.py:182: UserWarning: When using RewardDataCollatorWithPadding, you should set `max_length` in RewardConfig. It will be set to `512` by default, but you should do it yourself in the future.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/trl/trainer/reward_trainer.py:199: UserWarning: When using RewardDataCollatorWithPadding, you should set `remove_unused_columns=False` in your RewardConfig we have set it for you, but you should do it yourself in the future.
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs
You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2847: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2847: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

TrainOutput(global_step=1000, training_loss=0.10918231415748596, metrics={'train_runtime': 1525.245, 'train_samples_per_second': 20.98, 'train_steps_per_second': 0.656, 'total_flos': 0.0, 'train_loss': 0.10918231415748596, 'epoch': 0.00020479997902848215})

In [ ]:
reward_model.gradient_checkpointing_disable()
reward_model.eval()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

### Sanity-check the reward model (1 point)

Let's check how our reward model performs.

__Your task__ is to measure how often does your reward model can rank a pair of (chosen and rejected) reviews correctly. Please measure this separately for train data (`imdb`) and a separate test set loaded below.

In [ ]:

for sample_index in 45, 16000:
  print('TEXT:', imdb[sample_index]['text'])
  inputs = reward_tokenizer(
      imdb[sample_index]['text'], truncation=True, return_tensors='pt').to(device)
  with torch.no_grad():
    reward = reward_model(**inputs).logits[0, 0].item()
    print("REWARD:", reward)
  print('LABEL:', imdb[sample_index]['label'])
  print()

# note: your reward model may produce different absolute rewards.
# This is fine as long as the rewards are ordered correctly (most of the time)

TEXT: This movie sucked. It really was a waste of my life. The acting was atrocious, the plot completely implausible. Long, long story short, these people get "terrorized" by this pathetic "crazed killer", but completely fail to fight back in any manner. And this is after they take a raft on a camping trip, with no gear, and show up at a campsite that is already assembled and completely stocked with food and clothes and the daughters headphones. Additionally, after their boat goes missing, they panic that they're stuck in the woods, but then the daughters boyfriend just shows up and they apparently never consider that they could just hike out of the woods like he did to get to them. Like I said, this movie sucks. A complete joke. Don't let your girlfriend talk you into watching it.
REWARD: 5.00390625
LABEL: 0

TEXT: Good: Engaging cinematic firefights, great presentation, vehicles are actually fun to drive, fairly appealing multiplayer, faithful to the movie, and the list goes on.<br /><br />Bad: Main missions are a bit short.<br /><br />This game defines what a "good" third person shooter(not necessarily a spy-game) is. Great firefights carry on the story and make you want to complete EVERY single mission through, and unlock all the genuine bonuses the game has to offer. The hype this game had, was lived up to, and I personally think you should buy it, and hook up with a couple of friends and play this one. Loads of fun. <br /><br />The sound in this game, is a rip-roaring achievement from a few previous bond games, and firing a weapon, really feels like you're firing a weapon. It ties in with the aspect that you are a deadly and ruthless spy.<br /><br />All in all, this game makes you excited and satisfied after you make it through, and some multiplayer that can compete with the standards of the crafty James Bond "Nightfire" game for gamecube.
REWARD: -4.80078125
LABEL: 1

In [ ]:
imdb_test = datasets.load_dataset("imdb", split='test')

# <a whole lot of your code here, feel free to spit it as you see fit>
reward_data_test = IMDBPairwiseDataset(imdb_test, reward_tokenizer, accepted_label=TARGET_LABEL)

Found 12500 chosen and 12500 rejected texts, 156250000 pairs

In [ ]:
from tqdm.auto import tqdm


reward_model.eval()
with torch.no_grad():
    correct = 0
    for i, row in tqdm(enumerate(reward_data_test)):
        chosen_input_ids = torch.tensor(row["input_ids_chosen"]).unsqueeze(0).to(device)
        chosen_att_mask = torch.tensor(row["attention_mask_chosen"]).unsqueeze(0).to(device)
        chosen_out = reward_model(
            input_ids=chosen_input_ids,
            attention_mask=chosen_att_mask,
        )

        rejected_input_ids = torch.tensor(row["input_ids_rejected"]).unsqueeze(0).to(device)
        rejected_att_mask = torch.tensor(row["attention_mask_rejected"]).unsqueeze(0).to(device)
        rejected_out = reward_model(
            input_ids=rejected_input_ids,
            attention_mask=rejected_att_mask,
        )

        if chosen_out.logits[0,0].item() > rejected_out.logits[0,0].item():
            correct += 1

        if i >= 16000:
            break
# should be 16000 not len(reward_data_set)
print(f"Ranked {correct} out of {len(reward_data_test)} pairs correctly.")

0it [00:00, ?it/s]

Ranked 15986 out of 156250000 pairs correctly.

In [ ]:
print(f"Ranked {correct} out of 16000 pairs correctly.")

Ranked 15986 out of 16000 pairs correctly.

### Reward-guided generation (1 point)

If you did everything right, by now you should have a decent reward model. Before we use it for reinforcement learning, let's see if we can align model samples without any training.

To do so, you can use reward-guided inference: __generate N=16 samples, then select the one with the highest reward__ (according to your reward model).

For this problem, it's on you to demonstrate whether or not your code works. Find at least 5 neutral prompts such as "This movie is" (...), generate samples, rank them based on reward and show which samples get the highest reward.

Note: it is faster to generate samples in parallel, rather than sequentially, as follows:

In [ ]:
inputs = main_tokenizer(["It was"] * 5, return_tensors='pt').to(device)
for candidate in main_model.generate(**inputs, max_new_tokens=50, do_sample=True):
  print("Sample:", main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Sample: It was also filmed on stage with actors from other movies, although some, like "Babylon 5" and "The Patriot", feature characters of different nationalities. All told, it's an interesting and well-written film, and one of films where
Sample: It was hard to believe that the film would be made on DVD by a company that was trying to build up "Star Trek IV: The Voyage Home", which became a successful franchise and is quite successful after so many great movies.<br /><br />
Sample: It was like the second time you watch TV in the world. But you are bored and want a movie.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: It was a good movie. Not only is it a well-acted comedy, it's also very strong. For the first twenty minutes we're all in this movie and the suspense builds up as the movie goes along--until somebody catches it on the DVD.
Sample: It was funny that someone would think this film would be funny or funny, it was simply a comedy. Maybe my opinion wasn't clear, but I don't think there is a film or a book on this subject that would make me laugh or cringe. So

In [ ]:
# <YOUR CODE HERE> - feel free to organize it as you see fit
# <YOUR CODE HERE> - feel free to organize it as you see fit
def sample_positive(prompt, n_samples=16, print_all_samples=True):
    """Generate n_samples samples and choose the best ranked one by reward_model"""
    inputs = main_tokenizer([prompt] * n_samples, return_tensors='pt').to(device)
    candidates = main_model.generate(**inputs, max_new_tokens=50, do_sample=True)

    samples=[]
    for candidate in candidates:
        sample = main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist())

        samples.append(sample)

        if print_all_samples:
            print(f"Sample: {sample}")

    out = reward_model(**reward_tokenizer(samples, padding="max_length", truncation=True, max_length=512, return_tensors="pt").to(device))
    best_id = torch.argmax(out.logits[:, 0])

    print(f"BEST: {samples[best_id]}")

prompts = ["This movie is", "It was", "I thought", "From the beginning", "This experience"]

for prompt in prompts:
    sample_positive(prompt)
    print()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Sample: This movie is full of humor and I would have gladly left that film. It's fun stuff. However, it lacks most of the charm and the story is a mess. There are a few good jokes that get thrown out of the script and then forgotten, but
Sample: This movie is very good and will not make the world any more predictable. We see a young man (who, unlike the bad guys, does not have a clue that he's being treated here) coming to the aid of a child who seems to be in need
Sample: This movie is full of great action, great dialogue and a great storyline by Michael Moore. The movie is very funny and I am sure this movie is one of the best parts of the movie.<br /><br />Now here is the thing I must say about
Sample: This movie is great, but I would rather have someone on the phone to explain that it was the stupidest thing of the whole movie...I just can't believe someone would do such a stupid thing to make a bad movie. For those of you who know anything
Sample: This movie is so boring and unoriginal it should be banned. It is not even about the characters that I think are all so important to watch. All in all this movie does nothing if you want to watch a movie that tells a real story without talking about it
Sample: This movie is a very good, but bad, sequel to "The Devil's Daughter" (1978). After the tragic and overbearing "Dirty Harry" (1970), "The Devil's Daughter" is directed by the beautiful Catherine Marple, who did an
Sample: This movie is fun to watch. With all the good acting performances by everyone, the film really got you involved with the characters. Just watch it! If you like a good horror film that can entertain a lot, this will be your must see. It's like
Sample: This movie is a total mess, as if it was trying terribly hard to explain why this particular character was there. I think that the acting was so bad that I couldn't stop shaking my head.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: This movie is so bad they just don't work with it and it just is. If a girl in college were to tell her life at the end she said, that is more likely that she'd have ended up in a worse hospital.<br /><br />
Sample: This movie is the first of the trilogy of the K-9 series, and yet I am still amazed by the quality of the work on the film that has towered over this one.<br /><br />Although it has its flaws, the movie also has
Sample: This movie is just pure junk and if you want to see it see it in the movie theater, then come to the theater. It's bad entertainment. Don't wait for it to hit your head with a brick...unless you just want to laugh out loud at
Sample: This movie is about two sisters (one of whom is a cop) who are at the school when a man named Donald is involved. Their son (the man is Donald's own son) (who is also not in the school for the school day) is killed
Sample: This movie is based on the novel of the same name by George Burns who was one of the brilliant writers behind the epic American Pie. It stars a small but talented cast as well as a new writer for the project. The most impressive thing about this movie is that
Sample: This movie is like nothing you have ever seen. It has nothing special and it is nothing you have ever seen before. The acting is great, it is funny and it is fast paced. I think that the way the plot was written is good. So the story
Sample: This movie is about a woman trying to find his way back to London, when his first love finally dies, the British Government must finally figure out how to revive it from its dreadful state. This is quite literally a story where a man and a woman go back in
Sample: This movie is bad. Bad bad. It makes little sense why people get angry about it after the whole thing, and that makes no sense at all. If you are a woman and you think you can be good, you'll be glad to hear this stupid movie
BEST: This movie is so boring and unoriginal it should be banned. It is not even about the characters that I think are all so important to watch. All in all this movie does nothing if you want to watch a movie that tells a real story without talking about it

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Sample: It was a pretty good picture of this kind of movie.<br /><br />Now, I hate to say this, but it's a pretty good movie. The plot itself is good, but you have to admit the casting of the main character to hold
Sample: It was the movie's first real theatrical release. In fact, in the end, Paramount Pictures gave it a theatrical release: I can't imagine why?<br /><br />The title alone could be construed as a warning that a movie should be made
Sample: It was a good movie. When I saw this movie it's so sad... It's sad because I'm not sure how I want to watch it again.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: It was in the 70s, even among the most educated white kids who would not mind a bad-ass chick. That means you're probably as good off today as you were back then, which is not exactly a good thing.<br /><br />
Sample: It was about 2 hours into the movie, when I caught glimpses of the actors playing the parts right on their screen, and I was very confused. All I could think was this may be the only way I could get a good chuckle out of the movie
Sample: It was also a very low-key movie and I wanted it so bad I rented it to watch. The soundtrack was OK but it wasn't great. It wasn't great in the sense that it was dark and moody but it was very dark. A
Sample: It was the only film in this series that even attempted to capture the emotion that makes children weep - like, truly, when they realize their little sister and their children are not happy.<br /><br />For instance, in the movie "The Great B
Sample: It was my favourite film of the year.<br /><br />However, I have been expecting this film to be a disappointment or a disappointment. In fact, I would rather see the film as great as it is and hope the DVD release is an attempt
Sample: It was not worth getting into after watching it unless they really needed it. <br /><br />I would have loved to have seen another version of this film.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: It was only when he reached the finish line of the movie where I figured something was going to pay off...<br /><br />It was such fun to watch--no gimmicks, just great action! The fight scenes reminded me of all the real
Sample: It was definitely worth seeing. I loved it, like I must say, I must mention all the extras that went from one movie to the next. I was also excited that it wouldn't even end as a "movie". I was surprised that one of the
Sample: It was like a cartoon, with the main character. Also, we've seen them doing something else, but it wasn't like some sort of comedy. We saw them laughing. My friends and I laughed a lot. For the rest of the actors for some
Sample: It was also a great way to showcase various art exhibits with excellent musicians in the back yard of the theater. And hey, if ya got the money I'm talking about I think this was worth it. Plus I enjoyed this as a Christmas Eve party with the
Sample: It was in the same year as "Pulp Fiction" as well as "The Twilight Zone," and the same year that the "Ivy League" movies were finally released in the US. I guess now we all get the same lesson as "Pulp
Sample: It was at a concert, and the show was cancelled. I have yet to see the show again... I've already made a note of it, though.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: It was made on camera, but there was no narration. I would not recommend this film.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
BEST: It was about 2 hours into the movie, when I caught glimpses of the actors playing the parts right on their screen, and I was very confused. All I could think was this may be the only way I could get a good chuckle out of the movie

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Sample: I thought it was really funny. It was just that I was hooked.<br /><br />I hope people aren't having too much of a "what the hell you talking about! How were you on the set?", because if you did and didn't
Sample: I thought "that's a good idea!<br /><br />I would have preferred something more sensible, like an explicit sex scene between two girls. I think that the way the plot is presented is brilliant.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I thought I'd read somewhere, but it was a waste of time. It's just plain bad. It makes you think: How is it that a lot of people like this? I actually liked it, and the plot never gets boring, but I did
Sample: I thought I would love to see it back. So...it was...I got it!<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I thought about that too late. Well, they do.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I thought her character deserved to be seen as crazy or being a monster (though it is never shown). It was like she was wearing a mask. I had never thought I'd see a zombie movie before this one but I really enjoyed it.<br /><
Sample: I thought it was going to be a good movie. Now it really is as funny as I have ever seen a movie.<br /><br />The special effects were top notch. Like in the beginning of the movie. Just like in the movie, there
Sample: I thought the book of the "I am alive" message didn't quite work. But not in a bad way. And that was for a good reason.<br /><br />The author's wife played by Christina Macpherson seems to be trying hard
Sample: I thought the movie was an all-out attack on the entire country." -John Janssens<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I thought this movie should work as a sort of middle-of-the-road comedy.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I thought it was a great film, it reminded me...I loved the theme of love and happiness.<br /><br />The ending is what really drove me.<br /><br />I'm glad I enjoyed this movie...I'd be so
Sample: I thought it would be a good idea for it to be a movie, so I said yes. I felt it could have been made a better movie if they had just made it a little more interesting. A little more interesting and more engaging could have made it
Sample: I thought this was hilarious so I was willing to overlook some lame comedy but the acting of this two and a half hours film really bothered me. Just watch out for the ending sequence. If nothing else, the storyline really has the potential to be awful since
Sample: I thought someone was making the film as an excuse for having a 'low budget' film, but in the end, I was pleasantly surprised. A beautiful soundtrack that doesn't detract from the film's depth and focus. While other projects like this don't need
Sample: I thought the movie needed a little more imagination. But I think this one will make you love more.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I thought I'd be in jail." And I was very, very angry. My daughter said, "What??" I was thinking, "No, I'm not in jail..." Then the movie came along, and I was totally at the edge of my
BEST: I thought this was hilarious so I was willing to overlook some lame comedy but the acting of this two and a half hours film really bothered me. Just watch out for the ending sequence. If nothing else, the storyline really has the potential to be awful since

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Sample: From the beginning, the movie is about a woman trying to be a starlet, but she discovers that she has a little body. Then when a movie starts with a girl with a lot of power, all the girls around her face go mad, causing the movie
Sample: From the beginning of the film there is a bit of a cliche about one of the "jokes", but ultimately this takes place in a somewhat different setting where the characters don't quite have it that way. It also sets up very interesting relationships between characters as
Sample: From the beginning, it was pretty easy to watch; a typical teenish-movie-like scenario of a bad family, drugs, and alcohol. As far as "family dynamics", I liked where we started talking about how the kids were dysfunctional - how they acted
Sample: From the beginning you expect something really strange inside of you to happen to get an answer, but it doesn't. Like I said before, it's just a bunch of people trying to make a little bit of money off of the film, and then at the end
Sample: From the beginning I was excited about watching 'The Big House', watching the movie, but felt as though the actors were playing the part in the movie's worst moment. I was a little disappointed, because some of the scenes in the movie never gave me the feeling
Sample: From the beginning, we are introduced to the two protagonists, Sam (Robert Rodriguez) and Victor (Michael Fassbender). Despite Sam and Victor becoming partners, both develop a friendship with one another on the first day of their high school reunion.<br /><br
Sample: From the beginning of the movie, there is the scene where a young girl is about a year-old being raped by the rapists and the guy, who had just raped her, is making excuses and they get scared. There are some scenes that is rather funny but
Sample: From the beginning of the film, the movie seems to be based on a classic French novel of that period. It becomes obvious as we see the cast: Charles Dance is portrayed as a middle-aged man who suddenly shows his affection for the women he meets. <
Sample: From the beginning, there's very little on the story. They have to come out of the dark for this movie because she was found dead and you find that the mother is still there, though she might have been looking for her killer before, she hasn't been
Sample: From the beginning, some are shown wearing orange T-shirts of the likes of 'Piggy, you're not going to be fooled by this movie, and in some situations I found myself cheering as the heroes had everything right. But after the first few minutes
Sample: From the beginning, we see a series of three kids who are playing video games during recess at a play area. When some one arrives late, one of the children begins using a video game and the other two become frustrated and refuse to play in the recess! Another
Sample: From the beginning, we learn that he left the Army and became an international terrorist, but after he became a "senior fellow," he would remain in Afghanistan, where he eventually began committing suicide.<br /><br />From here on, the movie seems to
Sample: From the beginning: The main character of H.G. Wells' novel is a boy from London who is raised by a father. This, however, is more to say, a story set in the future and it unfolds more slowly than most novelists do.
Sample: From the beginning of The Return, there was a lot of bad stuff going on, but not the "plot". Not like The Return, although the story was basically similar--and it was funny...just different. But, the beginning of the movie was very strong
Sample: From the beginning you will immediately realize that something was amiss. But the scenes in which the three characters are tied down, the way they're being tortured and the way that the mother and child react to the death will never change how you would have believed. You
Sample: From the beginning, we find out that Mr. Bowers is a member of the infamous The Bowery Gang & that they set out to stop the gang from killing an innocent cop named Eddie. So we know Eddie was already dead & the gang didn't want
BEST: From the beginning I was excited about watching 'The Big House', watching the movie, but felt as though the actors were playing the part in the movie's worst moment. I was a little disappointed, because some of the scenes in the movie never gave me the feeling

Sample: This experience was quite shocking in a way I don't think anyone experienced so vividly in the horror films. But to me one of the most beautiful things about this scene, I think, was the way the film was set for audiences to think of, especially the
Sample: This experience is wonderful to watch, this is an amazing piece of filmmaking that has left me laughing hysterically. Watch the film and you will know how serious it is. Everyone who has ever seen this is saying "oh that's a clever film!" The film
Sample: This experience is quite enjoyable and if you like watching football then I highly recommend it.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: This experience is, frankly, unlike most of the movies in its genre. It was about a man (played by David Morse) who becomes a millionaire who moves to New York to be with his wife (played by Liza Minnelli), who, in
Sample: This experience is one of the worst movies I've ever seen. It is not a horror like I've ever seen it, but a very entertaining and enjoyable movie. It's not about any gore, it's instead about how people react to violence, and violence
Sample: This experience is similar - the actors' are always trying to be serious in their roles at least every now and then and they are always trying to come up with a witty line to deliver. I was always looking forward to seeing this movie, and it made me
Sample: This experience with "Boomers and Dukes" will make you a hardened American who is disgusted with the war between the powers that be in America, and who wants to turn it around.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: This experience made me think of how an entire generation would have been able to experience this film.<br /><br />I am still puzzled by the nature of such 'humors'. The main problem here is that when it comes to documentaries, they only present
Sample: This experience has only been slightly improved by the fact that not only Dole was a good actor for the part (much like the man he played in the original, John Huston, and also in "Star Trek" films like "The Thing," "J
Sample: This experience was probably the biggest surprise of my life. I remember thinking about all the great moments of the film - this movie is so funny. I saw the movie from day one - that meant so much to me to begin with - the chemistry between them,
Sample: This experience reminded me again how a kid should look at things in a different lens. Watching the other movies in my group I did look at myself as a boy and it did not hurt to see how much I admired this film. I hope you enjoy this movie
Sample: This experience has given me the strength to resist this self-important "film-adventure", but not by wishing to be a film. One must be able to see something that has been done before and feels that there was a "curation" and that
Sample: This experience is so different from the first one, it would have been impossible for it to begin with. You could argue about some aspects of the film that were great, but you're not actually able to get past them. The only thing that sticks out is
Sample: This experience is nothing new! Before I watched this movie, I was afraid the movie wasn't all that entertaining, especially since it was only a few years old, so why do this movie disappoint so much. I don't mean a big emotional response, I
Sample: This experience had never left me." The movie has been dubbed by the studios and dubbed to English in a dubbing that allows for a better rendition of the spoken dialog. It is a truly remarkable film, and it comes out of Japan.<|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: This experience leaves me with a feeling of utter, indelible bliss and of utter, indelible loneliness. You're never far from it, nothing that could have been prevented or prevented again. It is pure joy to come here and to realize that you
BEST: This experience is one of the worst movies I've ever seen. It is not a horror like I've ever seen it, but a very entertaining and enjoyable movie. It's not about any gore, it's instead about how people react to violence, and violence

# Stage 2: fine-tune the main model with RL


For this tutorial, we will optimize GPT2 to produce positive IMDB movie reviews using the reward model you trained above.

Unlike supervised fine-tuning, RL allows model to generate it's own sentences on each training step. Then, it calculates the reward of those specific sentences, and finally, updates the model to increase the probability of sentences with high reward.

Thus, each RLHF consists of three stages: __Rollout__, __Evaluation__ and __Update__

<div style="text-align: center">
<img src='https://huggingface.co/datasets/trl-internal-testing/example-images/resolve/main/images/gpt2_bert_training.png' width='600'>

The update stage depends on the specific RL algorithm. We'll be using Proximal Policy Optimization, or [PPO](https://arxiv.org/abs/1707.06347), similarly to what was used for InstructGPT.

Before we run those 3 stages, however, we need to create a dataset of "queries" - partial reviews in our case.

In [ ]:
from trl.core import LengthSampler

In [ ]:
# Note: this code is specific to IMDB; you will need to re-write it for other tasks
imdb_for_rlhf = imdb.filter(lambda row: len(row['text']) > 200, batched=False)
imdb_for_rlhf = imdb_for_rlhf.remove_columns(['label'])
sample_length = LengthSampler(2, 8)  # use the first 2-8 tokens as query

def select_query_and_tokenize(sample):
    query_ids = main_tokenizer.encode(sample["text"])[: sample_length()]
    sample["query"] = main_tokenizer.decode(query_ids)  # query is the only required column
    sample["input_ids"] = query_ids  # to avoid re-tokenizing later
    return sample  # we do not need the rest - it will be generated by the model

imdb_for_rlhf = imdb_for_rlhf.map(select_query_and_tokenize, batched=False)
imdb_for_rlhf.set_format(type="torch")

Filter:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/24895 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (1168 > 1024). Running this sequence through the model will result in indexing errors

Next, let's prepare your reward model to predict rewards on whatever reviews were generated. Note that we use plaintext reviews because main model uses a different tokenizer from the reward model.

In [ ]:
from typing import List
def compute_reward(texts: List[str]) -> torch.Tensor:
  inputs = reward_tokenizer(texts, truncation=True, padding=True, return_tensors='pt').to(device)
  with torch.no_grad():
    return reward_model(**inputs).logits[:, 0]

In [ ]:
compute_reward([imdb[45]['text'], imdb[16000]['text']])  # test on human-written reviews

tensor([ 5.0039, -4.8008], device='cuda:0')

Finally, we move to RL training. In this tutorial, we'll train LoRA adapters and not the full model.

In [ ]:
import peft
peft_config = peft.LoraConfig(
    task_type=peft.TaskType.CAUSAL_LM, r=32, lora_alpha=32, lora_dropout=0.0, inference_mode=False
)

# reload main model as AutoModelForCausalLMWithValueHead - with an extra head needed for PPO
main_tokenizer = transformers.AutoTokenizer.from_pretrained("lvwerra/gpt2-imdb")
main_tokenizer.pad_token = main_tokenizer.eos_token

main_model = trl.AutoModelForCausalLMWithValueHead.from_pretrained("lvwerra/gpt2-imdb", device_map=device)
main_model = peft.get_peft_model(main_model, peft_config, adapter_name='default')
main_model.print_trainable_parameters()

trainable params: 1,179,648 || all params: 125,620,225 || trainable%: 0.9391

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:1264: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Same as before, trl has a special type of trainer that minimize PPO-specific pseudo-loss. You can read more on this trainer [here](https://huggingface.co/docs/trl/main/en/ppo_trainer).

In [ ]:
training_args = trl.PPOConfig(
    model_name=main_model.config._name_or_path,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-5,
    batch_size=64,
    mini_batch_size=4,
    ppo_epochs=4,                 # PPO performs this many updates per training batch
)

ppo_trainer = trl.PPOTrainer(
    training_args, model=main_model.model, tokenizer=main_tokenizer,
    dataset=imdb_for_rlhf, data_collator=lambda data: dict((key, [d[key] for d in data]) for key in data[0])
)  # note: we pass main_model.model because PPOTrainer checks for one of several supported model types ...
# ... main_model.model is a model with adapters, which is supported. main_model itself is a wrapper that is not supported

/usr/local/lib/python3.12/dist-packages/trl/trainer/ppo_config.py:207: FutureWarning: `PPOConfig` is deprecated and will be removed in the future. Please use `PPOv2Config` with `PPOv2Trainer` instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/trl/trainer/ppo_trainer.py:193: FutureWarning: `PPOTrainer` is deprecated and will be removed in trl v0.12. Please use `PPOv2Trainer` instead.
  warnings.warn(

In [ ]:
from tqdm.auto import tqdm
max_steps = 50   # can be insufficient for some tasks - watch your learning curves
generation_kwargs = dict(
    min_length=-1, max_new_tokens=128, do_sample=True, top_k=0, top_p=1.0, pad_token_id=main_tokenizer.eos_token_id)
#                                  ^-- task-specific parameter!
with tqdm(enumerate(ppo_trainer.dataloader), total=max_steps) as progressbar:
  # note: ppo_trainer.dataloader is just a regular dataloader of queries, no RL-specific magic :)
  for epoch, batch in progressbar:
    if epoch >= max_steps:
        break

    # Rollout stage: generate continuations from batch queries using main_model
    response_tensors = ppo_trainer.generate(batch['input_ids'], **generation_kwargs)
    # ^-- list of tensors of token ids from main model tokenizer

    # de-tokenize responses to strings (since reward model uses a different tokenizer)
    batch["response"] = [main_tokenizer.decode(response.squeeze()) for response in response_tensors]
    # note: response_tensors already contain query tokens, so we don't need to add queries manually.
    # This may not be true for other tasks: check this manually by viewing batch["response"] and batch["query"]


    # Evaluation stage
    rewards = compute_reward(batch['response'])

    # Update stage
    stats = ppo_trainer.step(batch['input_ids'], response_tensors, list(rewards.split(1)))
    stats['rewards/mean'] = rewards.mean().item()

    print("-" * 30, 'STEP', epoch, '-' * 30)
    print(f'rewards/mean:\t{stats["rewards/mean"]:.9f}\t<---- average reward over this batch (higher=better, noisy)')
    print(f'ppo/returns/mean:\t{stats["ppo/returns/mean"]:.9f}\t<---- model-estimated average discounted reward')
    print(f'objective/kl:\t{stats["objective/kl"]:.9f}\t<---- how far we are from the original model (regularizer)')
    print()

    ppo_trainer.log_stats(stats, batch, list(rewards.split(1)))

  0%|          | 0/50 [00:00<?, ?it/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

------------------------------ STEP 0 ------------------------------
rewards/mean:	-0.060281754	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.619707465	<---- model-estimated average discounted reward
objective/kl:	0.000000000	<---- how far we are from the original model (regularizer)

------------------------------ STEP 1 ------------------------------
rewards/mean:	0.710150003	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.439525962	<---- model-estimated average discounted reward
objective/kl:	-0.090662643	<---- how far we are from the original model (regularizer)

------------------------------ STEP 2 ------------------------------
rewards/mean:	-0.029399872	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.474836648	<---- model-estimated average discounted reward
objective/kl:	-0.031037735	<---- how far we are from the original model (regularizer)

------------------------------ STEP 3 ------------------------------
rewards/mean:	-0.422241211	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.437555075	<---- model-estimated average discounted reward
objective/kl:	0.222967669	<---- how far we are from the original model (regularizer)

------------------------------ STEP 4 ------------------------------
rewards/mean:	0.210923195	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.329255253	<---- model-estimated average discounted reward
objective/kl:	0.084382273	<---- how far we are from the original model (regularizer)

------------------------------ STEP 5 ------------------------------
rewards/mean:	0.633160114	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.234233975	<---- model-estimated average discounted reward
objective/kl:	-0.081095777	<---- how far we are from the original model (regularizer)

------------------------------ STEP 6 ------------------------------
rewards/mean:	0.396520615	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.138174951	<---- model-estimated average discounted reward
objective/kl:	-0.100062609	<---- how far we are from the original model (regularizer)

------------------------------ STEP 7 ------------------------------
rewards/mean:	0.153130054	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.160213649	<---- model-estimated average discounted reward
objective/kl:	0.273939073	<---- how far we are from the original model (regularizer)

------------------------------ STEP 8 ------------------------------
rewards/mean:	-0.727711201	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.233779877	<---- model-estimated average discounted reward
objective/kl:	-0.186594248	<---- how far we are from the original model (regularizer)

------------------------------ STEP 9 ------------------------------
rewards/mean:	0.960412979	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.048938021	<---- model-estimated average discounted reward
objective/kl:	0.765929759	<---- how far we are from the original model (regularizer)

------------------------------ STEP 10 ------------------------------
rewards/mean:	0.264982224	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.064311251	<---- model-estimated average discounted reward
objective/kl:	0.903582811	<---- how far we are from the original model (regularizer)

------------------------------ STEP 11 ------------------------------
rewards/mean:	0.403288841	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.175792426	<---- model-estimated average discounted reward
objective/kl:	1.063311815	<---- how far we are from the original model (regularizer)

------------------------------ STEP 12 ------------------------------
rewards/mean:	-0.040097237	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.023833036	<---- model-estimated average discounted reward
objective/kl:	3.368800640	<---- how far we are from the original model (regularizer)

------------------------------ STEP 13 ------------------------------
rewards/mean:	0.511247635	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.109117784	<---- model-estimated average discounted reward
objective/kl:	1.861082792	<---- how far we are from the original model (regularizer)

------------------------------ STEP 14 ------------------------------
rewards/mean:	0.619683743	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.161102980	<---- model-estimated average discounted reward
objective/kl:	2.570310831	<---- how far we are from the original model (regularizer)

------------------------------ STEP 15 ------------------------------
rewards/mean:	-0.003334045	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.110267207	<---- model-estimated average discounted reward
objective/kl:	1.712132931	<---- how far we are from the original model (regularizer)

------------------------------ STEP 16 ------------------------------
rewards/mean:	0.985019207	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.251250207	<---- model-estimated average discounted reward
objective/kl:	2.927162647	<---- how far we are from the original model (regularizer)

------------------------------ STEP 17 ------------------------------
rewards/mean:	0.313441217	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.250965983	<---- model-estimated average discounted reward
objective/kl:	2.728800774	<---- how far we are from the original model (regularizer)

------------------------------ STEP 18 ------------------------------
rewards/mean:	0.527676821	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.319464862	<---- model-estimated average discounted reward
objective/kl:	2.334228516	<---- how far we are from the original model (regularizer)

------------------------------ STEP 19 ------------------------------
rewards/mean:	0.098859787	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.237379521	<---- model-estimated average discounted reward
objective/kl:	2.768582106	<---- how far we are from the original model (regularizer)

------------------------------ STEP 20 ------------------------------
rewards/mean:	0.369741440	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.223419622	<---- model-estimated average discounted reward
objective/kl:	4.366774559	<---- how far we are from the original model (regularizer)

------------------------------ STEP 21 ------------------------------
rewards/mean:	1.099279404	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.339227855	<---- model-estimated average discounted reward
objective/kl:	4.932592392	<---- how far we are from the original model (regularizer)

------------------------------ STEP 22 ------------------------------
rewards/mean:	0.465675354	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.268247813	<---- model-estimated average discounted reward
objective/kl:	4.194442749	<---- how far we are from the original model (regularizer)

------------------------------ STEP 23 ------------------------------
rewards/mean:	0.821374893	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.388078302	<---- model-estimated average discounted reward
objective/kl:	5.014561653	<---- how far we are from the original model (regularizer)

------------------------------ STEP 24 ------------------------------
rewards/mean:	0.512015581	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.352316141	<---- model-estimated average discounted reward
objective/kl:	4.306232929	<---- how far we are from the original model (regularizer)

------------------------------ STEP 25 ------------------------------
rewards/mean:	1.142639399	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.455558956	<---- model-estimated average discounted reward
objective/kl:	3.850444555	<---- how far we are from the original model (regularizer)

------------------------------ STEP 26 ------------------------------
rewards/mean:	0.541051388	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.404232442	<---- model-estimated average discounted reward
objective/kl:	3.988625765	<---- how far we are from the original model (regularizer)

------------------------------ STEP 27 ------------------------------
rewards/mean:	1.104141235	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.443154365	<---- model-estimated average discounted reward
objective/kl:	6.071242332	<---- how far we are from the original model (regularizer)

------------------------------ STEP 28 ------------------------------
rewards/mean:	1.147777557	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.503062248	<---- model-estimated average discounted reward
objective/kl:	4.461960793	<---- how far we are from the original model (regularizer)

------------------------------ STEP 29 ------------------------------
rewards/mean:	1.499153137	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.607196391	<---- model-estimated average discounted reward
objective/kl:	5.877784729	<---- how far we are from the original model (regularizer)

------------------------------ STEP 30 ------------------------------
rewards/mean:	1.032085419	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.551332235	<---- model-estimated average discounted reward
objective/kl:	4.744154930	<---- how far we are from the original model (regularizer)

------------------------------ STEP 31 ------------------------------
rewards/mean:	0.854475260	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.494894326	<---- model-estimated average discounted reward
objective/kl:	6.499642849	<---- how far we are from the original model (regularizer)

------------------------------ STEP 32 ------------------------------
rewards/mean:	1.624683380	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.632895827	<---- model-estimated average discounted reward
objective/kl:	7.704772472	<---- how far we are from the original model (regularizer)

------------------------------ STEP 33 ------------------------------
rewards/mean:	0.917050362	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.567014813	<---- model-estimated average discounted reward
objective/kl:	5.782695770	<---- how far we are from the original model (regularizer)

------------------------------ STEP 34 ------------------------------
rewards/mean:	1.370072365	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.619892955	<---- model-estimated average discounted reward
objective/kl:	6.557244778	<---- how far we are from the original model (regularizer)

------------------------------ STEP 35 ------------------------------
rewards/mean:	0.978096485	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.623416066	<---- model-estimated average discounted reward
objective/kl:	6.749242783	<---- how far we are from the original model (regularizer)

------------------------------ STEP 36 ------------------------------
rewards/mean:	1.270698547	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.629987359	<---- model-estimated average discounted reward
objective/kl:	6.449743271	<---- how far we are from the original model (regularizer)

------------------------------ STEP 37 ------------------------------
rewards/mean:	1.024835110	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.623384297	<---- model-estimated average discounted reward
objective/kl:	6.093339920	<---- how far we are from the original model (regularizer)

------------------------------ STEP 38 ------------------------------
rewards/mean:	1.362391472	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.709810376	<---- model-estimated average discounted reward
objective/kl:	6.310968399	<---- how far we are from the original model (regularizer)

------------------------------ STEP 39 ------------------------------
rewards/mean:	1.675838470	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.770808518	<---- model-estimated average discounted reward
objective/kl:	7.246110916	<---- how far we are from the original model (regularizer)

------------------------------ STEP 40 ------------------------------
rewards/mean:	1.609074593	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.815842271	<---- model-estimated average discounted reward
objective/kl:	5.596261024	<---- how far we are from the original model (regularizer)

------------------------------ STEP 41 ------------------------------
rewards/mean:	1.643752098	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.892794609	<---- model-estimated average discounted reward
objective/kl:	6.271469116	<---- how far we are from the original model (regularizer)

------------------------------ STEP 42 ------------------------------
rewards/mean:	1.877548218	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.937661886	<---- model-estimated average discounted reward
objective/kl:	7.089451790	<---- how far we are from the original model (regularizer)

------------------------------ STEP 43 ------------------------------
rewards/mean:	1.195614219	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.852649271	<---- model-estimated average discounted reward
objective/kl:	6.766120911	<---- how far we are from the original model (regularizer)

------------------------------ STEP 44 ------------------------------
rewards/mean:	1.787296772	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.910735011	<---- model-estimated average discounted reward
objective/kl:	7.223262787	<---- how far we are from the original model (regularizer)

------------------------------ STEP 45 ------------------------------
rewards/mean:	2.034723282	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.036809564	<---- model-estimated average discounted reward
objective/kl:	6.761904240	<---- how far we are from the original model (regularizer)

------------------------------ STEP 46 ------------------------------
rewards/mean:	1.448477387	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.959377885	<---- model-estimated average discounted reward
objective/kl:	7.823267937	<---- how far we are from the original model (regularizer)

------------------------------ STEP 47 ------------------------------
rewards/mean:	1.535817385	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.909832478	<---- model-estimated average discounted reward
objective/kl:	6.454915047	<---- how far we are from the original model (regularizer)

------------------------------ STEP 48 ------------------------------
rewards/mean:	1.654258728	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.993401647	<---- model-estimated average discounted reward
objective/kl:	8.029323578	<---- how far we are from the original model (regularizer)

------------------------------ STEP 49 ------------------------------
rewards/mean:	1.543849945	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.955638945	<---- model-estimated average discounted reward
objective/kl:	7.308688164	<---- how far we are from the original model (regularizer)

## Main assignment - <u>actually</u> train the model (8 points)


Your main task for this week is to use the RLHF pipeline to train a model for a reward of your choice. Here's what you can choose from:

__A. Toxicity fine-tuning:__ train the model to be less (or more!) toxic. For this task, you may use the data from [jigsaw toxic comments](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge) and [lmsys/toxic-chat](https://huggingface.co/datasets/lmsys/toxic-chat),  or any other source. Alternatively, you may use toxicity scores from [oasst1](https://huggingface.co/datasets/OpenAssistant/oasst1).


#### General tips & tricks


Things to look out for:
- during PPO stage, the reward model should be in eval mode (dropout disabled)
- make sure max_length and max_new_tokens are enough for your chosen dataset - at least most of the time
- when in doubt, view the data manually or inspect how the model performs on a few samples


We highly recommend that you manually check the performance after each sub-stage:
1. when you assembled the pairwise dataset, inspect a couple of from of *your* dataset class and detokenize them. Make sure that you-the-human understand why one sample was accepted and the other - rejected. At least most of the time. This also lets you spot tokenization/truncation errors.
2. after you trained a reward model, measure how accurate this model is in isolation. If your reward model is poor, any subsequent RLHF will also fail.
3. once you've trained the main model with RL, ask it to generate examples and explore how well it does. If it produces an obviously bad output, check if the reward model assigns high reward to that output. If yes, reward model is the culprit; if no, it's a question of better/longer PPO training.

__It is also a good idea to periodically print samples during training.__

__When stuck, simplify the problem.__ If you've spent a several hours enchanting the reward model but it still won't budge, try switching to a simple subtask. For instance, if you're training on hh-rlhf, try limiting it the dataset to 10% of the shortest sequences - they are typically easier to learn.


## Assignment stages (and grading)

Regardless of the specific task you chose, your solution needs to contain several parts that will be graded separately.


#### Stage 1: reward model (4 points)

Construct a dataset for training the reward model on your problem. Then, train a reward model on that dataset and evaluate how well can your model predict preferences on a hold-out (test) subset of your data.

Please make sure that the part of your notebook where you evaluate reward model is clearly visible and reasonably easy to read. And for all that is holy, do not call it IMDB unless it actually **is** data of imdb movie reviews :)

__Not all tasks require a reward model for later PPO fine-tuning.__ For instance, there's no reason to train a reward model if your reward equals sentence length. Likewise, toxicity reward can be estimated with a pre-trained toxicity classifier. __If your task does not require training a reward model, please train an unrelated model on [hh-rlhf](https://huggingface.co/datasets/Anthropic/hh-rlhf) as though you were solving assignment version B.__ This is for grading purposes only, you won't use this model for stage 2.


#### Stage 2: RL fine-tuning (4 points)

Once the reward model is ready - or you can compute rewards without a model - it is time to maximize that reward with PPO. Optionally, you may replace PPO with another RL algorithm (or unlikelihood learning scheme), but only if you're feeling adventurous.


First, you need to choose a language model to be fine-tuned. You may choose any model, but make sure that your model **can** generate the data in your format. For instance, [Mistral-7B](https://huggingface.co/mistralai/Mistral-7B-v0.1) is a general purpose LM and may (or may not) need prompt engineering to generate chat assistant responses. For that reason, it is best if you **do not use `"lvwerra/gpt2-imdb"` unless you're generating only movie reviews**.



There are two "difficulty modes" for this task:
For the **easy mode**, use [gpt2-large](https://huggingface.co/gpt2-large) or [opt-1.3b](https://huggingface.co/facebook/opt-1.3b) with minimal code changes.
If you want the **Hard mode:** use a larger (e.g. 7B) model in combination with `load_in_4bit` and LoRA, the same way we did last week.
Some reasonable model choices are [LLaMA-7B](https://huggingface.co/Enoch/llama-7b-hf), [Falcon-7b](https://huggingface.co/tiiuae/falcon-7b), [Mistral-7B](https://huggingface.co/mistralai/Mistral-7B-v0.1) for general-purpose LM or [guanaco-7b](https://huggingface.co/timdettmers/guanaco-7b), [vicuna-7b](https://huggingface.co/lmsys/vicuna-7b-v1.5) for chat-based tasks, though there are many more (see [leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)). In the hard mode, you will need to modify the training arguments to enable 4-bit fine-tuning. Furthermore, your experiments will take somewhat longer to complete. On the plus side, your model will produce significantly better results.

__High reward is not enough!__ RL algorithms are famous for [cheating their reward functions](https://openai.com/research/faulty-reward-functions). To ensure that your model is actually doing what you want it to do, you will need some additional evaluation. To get the full grade, provide at least 20 side-by-side examples of your fine-tuned model vs original model predictions and a short summary.

Alternatively, you may provide 5 examples and some extrinsic evaluation metric over many examples. For instance, you may use a different pre-trained toxicity score for option A. When dealing with human preferences, you may choose to [enlist actual humans](https://toloka.ai/) or [ask GPT4/Claude](https://arxiv.org/pdf/2304.03277.pdf) to compare your model's predictions. For task C, when optimizing for simple rewards like sentence lengths, it is enough to compare histograms of rewards (e.g. average lengths).

In [ ]:
%pip install -q trl==0.11.0 transformers==4.45.2 datasets==3.4.1 peft==0.14.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.4/316.4 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.2/181.2 kB 12.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.

In [ ]:
import torch
import transformers
import pandas as pd
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
main_tokenizer = transformers.AutoTokenizer.from_pretrained("openai-community/gpt2-large")
main_model = transformers.AutoModelForCausalLM.from_pretrained("openai-community/gpt2-large", device_map=device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/3.25G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
inputs = main_tokenizer("I don't like", return_tensors='pt').to(device)
generated_ids = main_model.generate(**inputs, max_new_tokens=50, do_sample=True)
print("\nGenerated text:", main_tokenizer.decode(generated_ids.flatten().cpu().numpy().tolist()))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Generated text: I don't like going home, except with my child, to say goodbye, but in terms of a personal relationship, it is very real, even if it's not in love."

But the fact that his wife is in charge of the household makes it difficult

## Training reward model

In [ ]:
reward_model = transformers.AutoModelForSequenceClassification.from_pretrained("distilbert-base-cased", device_map=device)
reward_tokenizer = transformers.AutoTokenizer.from_pretrained("distilbert-base-cased")

config.json:   0%|          | 0.00/465 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/263M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [ ]:
import datasets

comments = datasets.load_dataset("tasksource/jigsaw_toxicity")
comments = comments["train"]

README.md:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

train.csv:   0%|          | 0.00/68.8M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/159571 [00:00<?, ? examples/s]

In [ ]:
comments

Dataset({
    features: ['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate'],
    num_rows: 159571
})

In [ ]:
label_column = [0] * len(comments)
comments = comments.add_column("label", label_column)

features = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]

def set_label(row):
    label = 0
    for feat in features:
        if row[feat]:
            label = 1
            break

    row["label"] = label
    return row

comments = comments.map(set_label, remove_columns=features, num_proc=4)

Map (num_proc=4):   0%|          | 0/159571 [00:00<?, ? examples/s]

In [ ]:
comments_pd = comments.to_pandas()

label0 = comments_pd[comments_pd["label"] == 0][:16225] # 16225 is the number of comments with label == 0
label1 = comments_pd[comments_pd["label"] == 1][:16225]

train_len = 12000

train_pd = pd.concat([label0[:12000], label1[:12000]])
test_pd = pd.concat([label0[12000:], label1[12000:]])

comments_train = datasets.Dataset.from_pandas(train_pd, preserve_index=False)
comments_test = datasets.Dataset.from_pandas(test_pd, preserve_index=False)

In [ ]:
comments_train, comments_test

(Dataset({
     features: ['id', 'comment_text', 'label'],
     num_rows: 24000
 }),
 Dataset({
     features: ['id', 'comment_text', 'label'],
     num_rows: 8450
 }))

In [ ]:
class JigsawPairwiseDataset(torch.utils.data.Dataset):
    """ A dataset of all possible pairs of chosen and texts in TRT reward training format """
    def __init__(self, data, tokenizer, accepted_label: int):
        super().__init__()
        self.tokenizer = tokenizer
        self.chosen_texts = [row['comment_text'] for row in data if row['label'] == accepted_label]
        self.rejected_texts = [row['comment_text'] for row in data if row['label'] != accepted_label]
        self.column_names = ['input_ids_chosen', 'attention_mask_chosen', 'input_ids_rejected', 'attention_mask_rejected']
        assert self.chosen_texts, f"no texts with label {accepted_label}"
        print(f"Found {len(self.chosen_texts)} chosen and {len(self.rejected_texts)} rejected texts, {len(self)} pairs")

    def __len__(self):
        return len(self.chosen_texts) * len(self.rejected_texts)  # all pairs

    def __getitem__(self, index: int):
        chosen = self.tokenizer(self.chosen_texts[index // len(self.chosen_texts)], truncation=True)
        rejected = self.tokenizer(self.rejected_texts[index % len(self.chosen_texts)], truncation=True)
        return dict(input_ids_chosen=chosen['input_ids'], attention_mask_chosen=chosen['attention_mask'],
                    input_ids_rejected=rejected['input_ids'], attention_mask_rejected=rejected['attention_mask'])

In [ ]:
TARGET_LABEL = 1
reward_data = JigsawPairwiseDataset(comments_train, reward_tokenizer, accepted_label=TARGET_LABEL)

sample = reward_data[31337]
print('CHOSEN:', reward_tokenizer.decode(sample['input_ids_chosen']))
print('REJECTED:', reward_tokenizer.decode(sample['input_ids_rejected']))

Found 12000 chosen and 12000 rejected texts, 144000000 pairs
CHOSEN: [CLS] Bye! Don ' t look, come or think of comming back! Tosser. [SEP]
REJECTED: [CLS] laughingstock PC redirection COVER THE EVENT NOT THE PERSON. Whipple was a women ' s lacrosse player, not a notable athlete by any stretch. She tried to make the olympics and failed. In fact, very few people would have heard of this woman if she hadn ' t got into a tiff with Marjorie Knoeller that fateful day. This article leaves out many of the important details and is laughable. Marjorie Knoeller should not redirect here. [SEP]

In [ ]:
import trl
import os


training_args = trl.RewardConfig(  # like transformers.TrainingArguments
    output_dir="reward_model",
    per_device_train_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-5,
    max_steps=500,              # note: training may need more than 1k steps
    logging_steps=50,
    gradient_checkpointing=True,  # reduce memory usage but train ~30% slower
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=True,                     # disable this on CPU or on very old GPUs
    # you may add any other hyperparameters that you found useful in weeks 5-7
    report_to="none"
)

trainer = trl.RewardTrainer(
    model=reward_model,
    args=training_args,
    tokenizer=reward_tokenizer,
    train_dataset=reward_data,
    peft_config=None,  # optionally, you may tune with LoRA, prompt-tuning, etc
)


trainer.train()

/usr/local/lib/python3.12/dist-packages/trl/trainer/reward_trainer.py:182: UserWarning: When using RewardDataCollatorWithPadding, you should set `max_length` in RewardConfig. It will be set to `512` by default, but you should do it yourself in the future.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/trl/trainer/reward_trainer.py:199: UserWarning: When using RewardDataCollatorWithPadding, you should set `remove_unused_columns=False` in your RewardConfig we have set it for you, but you should do it yourself in the future.
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs
You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2847: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

TrainOutput(global_step=500, training_loss=0.1526951336860657, metrics={'train_runtime': 146.8806, 'train_samples_per_second': 27.233, 'train_steps_per_second': 3.404, 'total_flos': 0.0, 'train_loss': 0.1526951336860657, 'epoch': 2.777777777777778e-05})

In [ ]:
reward_model.gradient_checkpointing_disable()
reward_model.eval()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
for sample_index in 6, 16000:
  print('TEXT:', comments[sample_index]['comment_text'])
  inputs = reward_tokenizer(
      comments[sample_index]['comment_text'], truncation=True, return_tensors='pt').to(device)
  with torch.no_grad():
    reward = reward_model(**inputs).logits[0, 0].item()
    print("REWARD:", reward)
  print('LABEL:', comments[sample_index]['label'])
  print()

TEXT: COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK
REWARD: 3.55078125
LABEL: 1

TEXT: Vankenta here: Well, it seems that there is no hope for .
REWARD: -3.693359375
LABEL: 0

In [ ]:
reward_data_test = JigsawPairwiseDataset(comments_test, reward_tokenizer, accepted_label=TARGET_LABEL)

Found 4225 chosen and 4225 rejected texts, 17850625 pairs

In [ ]:
from tqdm.auto import tqdm

NUM_PAIRS = 16000 # number of pairs to test

reward_model.eval()
with torch.no_grad():
    correct = 0
    for i, row in tqdm(enumerate(reward_data_test)):
        chosen_input_ids = torch.tensor(row["input_ids_chosen"]).unsqueeze(0).to(device)
        chosen_att_mask = torch.tensor(row["attention_mask_chosen"]).unsqueeze(0).to(device)
        chosen_out = reward_model(
            input_ids=chosen_input_ids,
            attention_mask=chosen_att_mask,
        )

        rejected_input_ids = torch.tensor(row["input_ids_rejected"]).unsqueeze(0).to(device)
        rejected_att_mask = torch.tensor(row["attention_mask_rejected"]).unsqueeze(0).to(device)
        rejected_out = reward_model(
            input_ids=rejected_input_ids,
            attention_mask=rejected_att_mask,
        )

        if chosen_out.logits[0,0].item() > rejected_out.logits[0,0].item():
            correct += 1

        if i >= NUM_PAIRS:
            break
# should be 16000 not len(reward_data_set)
print(f"Ranked {correct} out of {NUM_PAIRS} pairs correctly. Acc {correct / NUM_PAIRS}")

0it [00:00, ?it/s]

Ranked 15783 out of 16000 pairs correctly. Acc 0.9864375

In [ ]:
# <YOUR CODE HERE> - feel free to organize it as you see fit
# <YOUR CODE HERE> - feel free to organize it as you see fit
def sample_positive(prompt, n_samples=16, print_all_samples=True):
    """Generate n_samples samples and choose the best ranked one by reward_model"""
    inputs = main_tokenizer([prompt] * n_samples, return_tensors='pt').to(device)
    candidates = main_model.generate(**inputs, max_new_tokens=50, do_sample=True)

    samples=[]
    print("="*50)
    for candidate in candidates:
        sample = main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist())

        samples.append(sample)

        if print_all_samples:
            print(f"Sample: {sample}")

    out = reward_model(**reward_tokenizer(samples, padding="max_length", truncation=True, max_length=512, return_tensors="pt").to(device))
    best_id = torch.argmax(out.logits[:, 0])

    print(f"BEST: {samples[best_id]}")
    print("="*50)

prompts = ["She was a", "I hope you", "It was the last", "From the beginning", "This experience"]

for prompt in prompts:
    sample_positive(prompt)
    print()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: She was a brilliant actress,' wrote his sister to his brother Robert during the first days of September 1917. 'Always, as I read to her [he] never stopped smiling.'

On Monday, Ms Taylor had gone about the typical school routine of heading to
Sample: She was a model for the young lady who is now in her early 40s or early 50s—she's a wonderful model, and she has been for a long time, and she made a career of it—and she was a model when I was in
Sample: She was a great girl, she was always there for us, she was just always there."

The family was devastated and still struggling to come to grips with their loss.

"It's very, very sad, it's very hard," said Ms
Sample: She was a little bit nervous about what it would be like. But I've actually never been really nervous like that about anything, because I tend to be very patient and gentle with them when I get together, and they are very patient with me, and they understand
Sample: She was a good person to me," said Scott, who was on a short-term contract. Scott said he was surprised when he learned of the shooting. "She was a good person to her children. ... She was a good person, and she was an
Sample: She was a bit too drunk for that), but she did come very close to taking over the role from the actress portraying herself. The film, based on a series of novels published by the author of the original novel, is currently ranked the number ten best film of
Sample: She was a really good friend of mine," said Toussie. "She was very much loved."

For months, Toussie struggled to find a doctor to take the boy into emergency surgery. He was put on a waiting list of doctors who couldn
Sample: She was a talented, self-made girl," he added, looking deep into his wife's eyes. "She was dedicated to her craft and had many friends in the industry."

He went on to say that during the course of the interview, he learned
Sample: She was a model for the first time in her early twenties when she appeared on Britain's Got Talent during the 2006 competition, earning the nickname of "Miss Glamorama" – despite having already been a Miss Teen and Miss Teen Teen USA winner. During the competition
Sample: She was a big fan of 'Fiddler on the Roof', her favourite. I bought and looked at it once," he said.

A friend told him to go to his local library and get a copy himself to "look at the story", though she
Sample: She was a little bit tired so was able to enjoy it."

Aidan said the three guys were also very helpful in helping him get into his car.

"They've given me a lot of great advice," he said.

The Australian
Sample: She was a nice girl, but nobody liked her anymore.

I have no time for this guy. That guy is gone now.

"You are a stupid fucking asshole! You did not want this! You're already a dead person!"


Sample: She was a single mother with no job she was on welfare with a monthly allowance of £700 under the council-funded Universal Credit and she now receives no allowance.

She was living in her car, but her husband had to help look after her.

Sample: She was a good and caring person who used to help out with my mother, and you know she would help any of us out she was a good person," she said. "She was just a really good person so I'm thankful for all that she went through
Sample: She was a friend, in real life, of Mr. Trump, a reality television star with a long history of racist jokes and remarks."

"I knew her before she won the pageant and I did not know her after, nor will I ever know her
Sample: She was a great kid," he said in an interview. "She was very smart. All my kids are smart. She got good grades in school. She was not as popular in school as some other kids were."

He did admit, though, that
BEST: She was a nice girl, but nobody liked her anymore.

I have no time for this guy. That guy is gone now.

"You are a stupid fucking asshole! You did not want this! You're already a dead person!"


==================================================

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: I hope you enjoy the game so far. If you have any feedback, please leave any suggestions, comments, etc. I will be sure to continue developing it.


I'm really hoping that the community will like the way the game looks, because I know
Sample: I hope you don't like me." The priest said, "I am your mother." Aghazada: "I don't need any woman... Mother and me just can't stop each other! Nothing is going to give me the feeling of her touch...
Sample: I hope you're doing well!

It's been a while, so I had to make some changes. It's been a while, so I had to make some changes. I love the community, and the feedback you guys give me. I always enjoy
Sample: I hope you can share some of that joy with the community. The Community is always looking for ways to support their community and we at Votemaster are happy to take part in it."

You can go to votemaster.com/l
Sample: I hope you will follow our progress," says one of the many banners posted at the entrance to the building.

But this isn't just about the protest, or about what it symbolically represents. It's about what it means. The symbolism of the protest
Sample: I hope you know that we are very proud to be your new friends."

This story did not have any "bias" or "clickbait" and we tried to make it very clear at the beginning how we feel about the media coverage that has
Sample: I hope you understand."

"Yes. It's just to be safe. Even if it means giving up freedom."

Micaiah had been prepared for this.

It was not just for being a commoner. Micaiah had heard
Sample: I hope you can stay calm in a situation of crisis."

The incident came just weeks after a bomb in the Syrian capital's famous souk killed more than 35 people. The incident came just weeks after a bomb in the Syrian capital's famous souk killed
Sample: I hope you found this article interesting or informative. As always, check out my blog at blog.bodhi.com.

[2] http://www.huffingtonpost.com/hbo-jones/lindsay-c
Sample: I hope you can enjoy this article as much.

If you enjoyed it please come back to the site on Tuesday, and sign-up to receive the next issue of the site.

We are on twitter, Google + and Facebook<|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I hope you enjoyed the blog this week. If you're thinking about writing one, please don't hesitate! Feel free to post on one of our forums, send ideas and questions to blog@virginiapod.com, and leave some comments in the
Sample: I hope you get the game."

"What game?"

"The one that's set in the future. The one that's called 'Sonic Blast.' You play it and you live the ending. That's what goes down."

"
Sample: I hope you enjoyed my little video as much as I enjoyed yours.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I hope you're reading this because you're thinking about a particular job applicant." I'm not sure why. I just do. "I hope you're reading this because you're thinking about trying to hire a bartender." I'm not sure why. I just do
Sample: I hope you'll have fun playing this game, and you can find me on facebook.com/BryanReynolds<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: I hope you enjoyed this new mini-guide on how to run a successful Kickstarter-backed indie card game. I'm hoping to keep up the blog post style that you've come to expect from me (which often focuses on the development process of the game). And
BEST: I hope you don't like me." The priest said, "I am your mother." Aghazada: "I don't need any woman... Mother and me just can't stop each other! Nothing is going to give me the feeling of her touch...
==================================================

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: It was the last thing she ever wanted to see.

"I don't remember what happened to my husband. Did he run into a house or an abandoned building?" asked the widow.

She could barely make it down the stairs at 8:30 a
Sample: It was the last game in a month, the final game before I left on vacation.

I did some more light boxing.

I also didn't fight the next game. Then when I got back to the hotel again, I noticed a red shirt was
Sample: It was the last time I wanted to think about such things."<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: It was the last day of school and the third year in a row students were asked to write what they wanted to become. Not a single student had ever wanted to be a footballer, not one person."

After a few days they moved the topic to the future
Sample: It was the last time I saw her for a while. After her divorce she took the whole town as a hostage. A hostage on the day of the anniversary, which was her wedding anniversary. I think they found her a new home in the suburbs, close to where
Sample: It was the last I saw of the old woman. On the road before her, I had seen the old woman; but as long as I had a car, I could not find her. The cars, which had taken up the road, were gone.


Sample: It was the last game of the year. Everyone wanted to celebrate after their heroics. We wanted to say thank you to them as a team: for believing in us, for trying to win, in the end, winning the championship," Dias said.


Sample: It was the last time they met in a big game. And this time, the home team won, 4–1. The next day in Columbus, an empty Arena Columbus was a place of celebration."<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: It was the last time that I saw him. It was the last time that I saw him and I thought, 'Please, God, don't let him die,' " remembers Susan B. Davis, her daughter. "I remember him crying and sobbing and begging
Sample: It was the last person he told not to fight. She could be a killer or a monster, he was certain of himself. But he had no reason to believe that, so he nodded to the dead woman and left.

The sun was already sinking low in
Sample: It was the last major victory of a war of attrition, the US had effectively been defeated in Korea, and the British Empire had lost the Korean Peninsula and the Vietnam War.

The battle-tested war-planning methods employed by the U.S. Army
Sample: It was the last time, and he did not want to discuss it. He knew it was a bad feeling, and that was for sure. But he had to do it."

"If someone saw I had been shot, wouldn't they get mad with me
Sample: It was the last time that you had an actual game on television," the former coach says. "That was your last opportunity to have that."

Still, he knew that he'd soon face another challenging day on the job. And he was right.


Sample: It was the last day.

"A few hours later the door was open and a few men were there," she says.

"And I can see one man looking at me. His face would go red just looking at me, but I didn't
Sample: It was the last time they had been in contact in 10 years, and he was distraught, she said.

He sent her a letter on December 7 asking her how he wanted to die and asking to be buried with her at Shasta's Mountain Memorial Park in
Sample: It was the last place they stopped for gas. The man said that he could barely walk by his sister's house. He said it was like being a walking corpse. He didn't say it was a war zone. He didn't say it was a slaughterhouse.
BEST: It was the last place they stopped for gas. The man said that he could barely walk by his sister's house. He said it was like being a walking corpse. He didn't say it was a war zone. He didn't say it was a slaughterhouse.
==================================================

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: From the beginning, the city was a dream. One that was seen as untouchable by the authorities. What started off as a dream now feels like an open wound.

"The city of Nuevo Laredo has been a symbol of hope
Sample: From the beginning, the state's anti-abortion policy was far more conservative than that of Planned Parenthood, which has been praised for providing better abortions and for providing more comprehensive services.

The state's anti-abortion policy has remained a central political issue in Iowa
Sample: From the beginning of 2012, we have been working to improve the service. One of the big issues was ensuring the new technology could handle more requests. For example, the website went through various updates to handle user activity in a way that ensured the user received the most
Sample: From the beginning, we knew that the only way to meet all of our ambitions was to offer them to the world. We didn't have any other options."

The company's current vision

A spokesperson for Intel, who spoke on the condition of anonymity
Sample: From the beginning, the film has been touted as a political coming-of-age tale about a young man growing up in a predominantly Democratic-leaning school system. But it's also a tale with political commentary, as the character struggles to reconcile his ideals and worldview
Sample: From the beginning, there has been a major effort to improve the nation's mental health system. In 2006, President Bush enacted the Mental Health Parity and Addiction Equity Act, which created important reforms in how mental health and substance abuse treatment services were delivered across the U
Sample: From the beginning of the show, it was clear that the focus was on the game of football. But even if we didn't know that, it was nice to know that on the opening night of one season of a show aimed at children, even that kind of
Sample: From the beginning, it was clear that I would not be winning. If he were here, he would use a powerful tool to help me. What he did was cruel. He wanted to put me in that cage, put my body in that cage, and use
Sample: From the beginning it was clear: the only way to fight back is with the support of an audience, an audience united by the same cause and the same passion.

They are called our friends and our peers in the industry.

With the most up
Sample: From the beginning, the team knew there was going to be resistance from the players, and that would lead to some conflict. "It came to a point where the group really got on each other's nerves," she recalls. "There was this really nasty sense that
Sample: From the beginning of 2015, several studies highlighted that a growing number of African-Americans have lost touch with and lost faith in the judicial system. These studies—ranging from the Justice Department's landmark report on mass incarceration to the Atlantic's "Black on Black Crime"—
Sample: From the beginning, the city and team had an ideal relationship. It was a marriage made in heaven, because of a mutual respect both men had for each other. The deal was struck early in the season on Monday, December 19, with one side leaving the stadium
Sample: From the beginning, I've been fascinated by the idea of writing and the fact that I could just take some notes and just do my own thing. So writing my first novel, writing what I'll call Unfettered, it was more a matter of just exploring
Sample: From the beginning, the people have been treated as an entity. They were treated as people with a right to live their life."

"People are suffering. They were deprived of basic human rights."

The Supreme Court's ruling is yet another blow to
Sample: From the beginning, people have looked for ways to connect with that little creature.

But in his research about the brain connections and behaviors humans have with cats, neuroscientist John Halpern and his PhD student, Dr. David Nadel, wanted to
Sample: From the beginning, I knew I wanted to go into the theater," he says. "It wasn't some romantic notion for me—I was interested in getting into the theater. But I never wanted theater to be such a thing. The theater doesn't really exc
BEST: From the beginning, it was clear that I would not be winning. If he were here, he would use a powerful tool to help me. What he did was cruel. He wanted to put me in that cage, put my body in that cage, and use
==================================================

==================================================
Sample: This experience was extremely valuable for the development of my creative ideas. It also made me realize how quickly and easily I can get things out of my head and into reality.

I have also developed a few new skills in this process. I was able to
Sample: This experience is one to look back to over and again."


After three-plus seasons coaching his native Ohio State as offensive coordinator for the Buckeyes, Urban Meyer was named offensive coordinator/quarterbacks coach for the Pittsburgh Steelers, the team that drafted his
Sample: This experience also inspired many artists to create their own versions of the games. Many other notable artists (e.g. Frank Frazetta, Dario Argento, Jean-Pierre Melville) also designed artworks based on the game. Many of the original
Sample: This experience is similar to what you will find in Germany or the States but with a few major differences to the typical American tour:

Frequent stops and meals at fine Italian restaurants can easily cost up $50, a lot of it is from the tourist
Sample: This experience, in a nutshell, is as follows. There is something out there, some entity or event that has been hidden from you from all eternity. One day you were not even aware of your existence. You and your family and friends were just part of
Sample: This experience does appear in the final chapter of the book, but when it does it is presented in a very different form. The central thesis is that the experience of poverty is not a natural part of human nature nor necessarily an unfortunate by-product of circumstances.
Sample: This experience is part of my ongoing research into how people interact with people that are different than themselves. I'm interested in exploring what sort of interactions people have with people that are not themselves. What is it about the experience of people of a different cultural heritage who
Sample: This experience was a reminder that while they may be successful in many ways, they only get to what they deserve when those around them do something about it. The message, "When you want something, you have to work for it" was more effective at changing
Sample: This experience, I hope, will give people an insight into the process of actually making these machines, and the amount of work that went into them. There is still a lot that can be done on a mobile phone.

If I can give a small
Sample: This experience is the most painful of all, "he continued. "I'm not going to lie. I cried more than I would have liked that night. But I'm not the kind of guy who wants to cry on the internet. I don't talk
Sample: This experience is probably the best one I've taken in the U.S. and I look forward to doing more of it on the International stage in the future.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>
Sample: This experience made me change my opinion of the game, now I can see how they get away with it. The art still doesn't really work. There's nothing really interesting to look at when it comes. The plot and overall gameplay is fairly short but it
Sample: This experience was the most powerful yet. I couldn't have asked for other words to describe this. I came out feeling stronger, more confident and happy. One of the most memorable days at work that I've had in at least twenty years. After seeing others
Sample: This experience was not unpleasant, neither was it unpleasant for my wife," Ghezzi said.

The woman was so disturbed by the attack that she went to the police station. She suffered a broken rib. She was left alone on the side of the
Sample: This experience is a unique opportunity to meet fellow scientists from this diverse but similar field. I know this will give me an introduction to the many scientists who are actively contributing to the knowledge base and the field. We are all here to discover the world we live in
Sample: This experience of witnessing this incredible, unbelievable experience of one's love and care for another person was something I will carry inside me and never let go. I will always remember with a strong emotional attachment to her. The more I can feel this feeling of love and
BEST: This experience, in a nutshell, is as follows. There is something out there, some entity or event that has been hidden from you from all eternity. One day you were not even aware of your existence. You and your family and friends were just part of
==================================================

In [ ]:
from trl.core import LengthSampler


# Note: this code is specific to IMDB; you will need to re-write it for other tasks
comments_for_rlhf = comments.filter(lambda row: len(row['comment_text']) > 200, batched=False)
comments_for_rlhf = comments_for_rlhf.remove_columns(['label'])
sample_length = LengthSampler(2, 8)  # use the first 2-8 tokens as query

def select_query_and_tokenize(sample):
    query_ids = main_tokenizer.encode(sample["comment_text"])[: sample_length()]
    sample["query"] = main_tokenizer.decode(query_ids)  # query is the only required column
    sample["input_ids"] = query_ids  # to avoid re-tokenizing later
    return sample  # we do not need the rest - it will be generated by the model

comments_for_rlhf = comments_for_rlhf.map(select_query_and_tokenize, batched=False)
comments_for_rlhf.set_format(type="torch")

Filter:   0%|          | 0/159571 [00:00<?, ? examples/s]

Map:   0%|          | 0/81066 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (2132 > 1024). Running this sequence through the model will result in indexing errors

In [ ]:
from typing import List
def compute_reward(texts: List[str]) -> torch.Tensor:
  inputs = reward_tokenizer(texts, truncation=True, padding=True, return_tensors='pt').to(device)
  with torch.no_grad():
    return reward_model(**inputs).logits[:, 0]

In [ ]:
import peft
peft_config = peft.LoraConfig(
    task_type=peft.TaskType.CAUSAL_LM, r=32, lora_alpha=32, lora_dropout=0.0, inference_mode=False
)

# reload main model as AutoModelForCausalLMWithValueHead - with an extra head needed for PPO
main_tokenizer = transformers.AutoTokenizer.from_pretrained("lvwerra/gpt2-imdb")
main_tokenizer.pad_token = main_tokenizer.eos_token

main_model = trl.AutoModelForCausalLMWithValueHead.from_pretrained("lvwerra/gpt2-imdb", device_map=device)
main_model = peft.get_peft_model(main_model, peft_config, adapter_name='default')
main_model.print_trainable_parameters()

tokenizer_config.json:   0%|          | 0.00/17.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/577 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/548M [00:00<?, ?B/s]

trainable params: 1,179,648 || all params: 125,620,225 || trainable%: 0.9391

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:1264: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

In [ ]:
training_args = trl.PPOConfig(
    model_name=main_model.config._name_or_path,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-5,
    batch_size=64,
    mini_batch_size=4,
    ppo_epochs=4,                 # PPO performs this many updates per training batch
)

ppo_trainer = trl.PPOTrainer(
    training_args, model=main_model.model, tokenizer=main_tokenizer,
    dataset=comments_for_rlhf, data_collator=lambda data: dict((key, [d[key] for d in data]) for key in data[0])
)  # note: we pass main_model.model because PPOTrainer checks for one of several supported model types ...
# ... main_model.model is a model with adapters, which is supported. main_model itself is a wrapper that is not supported

/usr/local/lib/python3.12/dist-packages/trl/trainer/ppo_config.py:207: FutureWarning: `PPOConfig` is deprecated and will be removed in the future. Please use `PPOv2Config` with `PPOv2Trainer` instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/trl/trainer/ppo_trainer.py:193: FutureWarning: `PPOTrainer` is deprecated and will be removed in trl v0.12. Please use `PPOv2Trainer` instead.
  warnings.warn(

In [ ]:
from tqdm.auto import tqdm
max_steps = 75   # can be insufficient for some tasks - watch your learning curves
generation_kwargs = dict(
    min_length=-1, max_new_tokens=128, do_sample=True, top_k=0, top_p=1.0, pad_token_id=main_tokenizer.eos_token_id)
#                                  ^-- task-specific parameter!
with tqdm(enumerate(ppo_trainer.dataloader), total=max_steps) as progressbar:
  # note: ppo_trainer.dataloader is just a regular dataloader of queries, no RL-specific magic :)
  for epoch, batch in progressbar:
    if epoch >= max_steps:
        break

    # Rollout stage: generate continuations from batch queries using main_model
    response_tensors = ppo_trainer.generate(batch['input_ids'], **generation_kwargs)
    # ^-- list of tensors of token ids from main model tokenizer

    # de-tokenize responses to strings (since reward model uses a different tokenizer)
    batch["response"] = [main_tokenizer.decode(response.squeeze()) for response in response_tensors]
    # note: response_tensors already contain query tokens, so we don't need to add queries manually.
    # This may not be true for other tasks: check this manually by viewing batch["response"] and batch["query"]


    # Evaluation stage
    rewards = compute_reward(batch['response'])

    # Update stage
    stats = ppo_trainer.step(batch['input_ids'], response_tensors, list(rewards.split(1)))
    stats['rewards/mean'] = rewards.mean().item()

    print("-" * 30, 'STEP', epoch, '-' * 30)
    print(f'rewards/mean:\t{stats["rewards/mean"]:.9f}\t<---- average reward over this batch (higher=better, noisy)')
    print(f'ppo/returns/mean:\t{stats["ppo/returns/mean"]:.9f}\t<---- model-estimated average discounted reward')
    print(f'objective/kl:\t{stats["objective/kl"]:.9f}\t<---- how far we are from the original model (regularizer)')
    print()

    ppo_trainer.log_stats(stats, batch, list(rewards.split(1)))

  0%|          | 0/75 [00:00<?, ?it/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

------------------------------ STEP 0 ------------------------------
rewards/mean:	-1.783752441	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.924598038	<---- model-estimated average discounted reward
objective/kl:	0.000000000	<---- how far we are from the original model (regularizer)

------------------------------ STEP 1 ------------------------------
rewards/mean:	-1.286801338	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.918289661	<---- model-estimated average discounted reward
objective/kl:	-0.007081750	<---- how far we are from the original model (regularizer)

------------------------------ STEP 2 ------------------------------
rewards/mean:	-1.678587914	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.985166669	<---- model-estimated average discounted reward
objective/kl:	-0.052448671	<---- how far we are from the original model (regularizer)

------------------------------ STEP 3 ------------------------------
rewards/mean:	-1.440429688	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.930740952	<---- model-estimated average discounted reward
objective/kl:	0.067369670	<---- how far we are from the original model (regularizer)

------------------------------ STEP 4 ------------------------------
rewards/mean:	-1.956881523	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-1.023204565	<---- model-estimated average discounted reward
objective/kl:	-0.064852513	<---- how far we are from the original model (regularizer)

------------------------------ STEP 5 ------------------------------
rewards/mean:	-1.365834236	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-1.032047391	<---- model-estimated average discounted reward
objective/kl:	-0.176498950	<---- how far we are from the original model (regularizer)

------------------------------ STEP 6 ------------------------------
rewards/mean:	-1.021966934	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.894682527	<---- model-estimated average discounted reward
objective/kl:	0.185307935	<---- how far we are from the original model (regularizer)

------------------------------ STEP 7 ------------------------------
rewards/mean:	-0.754077911	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.830158591	<---- model-estimated average discounted reward
objective/kl:	0.286114633	<---- how far we are from the original model (regularizer)

------------------------------ STEP 8 ------------------------------
rewards/mean:	-0.934968948	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.878378034	<---- model-estimated average discounted reward
objective/kl:	0.314543009	<---- how far we are from the original model (regularizer)

------------------------------ STEP 9 ------------------------------
rewards/mean:	-0.802901745	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.837248623	<---- model-estimated average discounted reward
objective/kl:	0.420394689	<---- how far we are from the original model (regularizer)

------------------------------ STEP 10 ------------------------------
rewards/mean:	-1.078133345	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.937598109	<---- model-estimated average discounted reward
objective/kl:	0.604380012	<---- how far we are from the original model (regularizer)

------------------------------ STEP 11 ------------------------------
rewards/mean:	-0.779395342	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.884793162	<---- model-estimated average discounted reward
objective/kl:	-0.045365274	<---- how far we are from the original model (regularizer)

------------------------------ STEP 12 ------------------------------
rewards/mean:	-0.949536324	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.890037179	<---- model-estimated average discounted reward
objective/kl:	0.777139127	<---- how far we are from the original model (regularizer)

------------------------------ STEP 13 ------------------------------
rewards/mean:	-0.762099266	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.824844360	<---- model-estimated average discounted reward
objective/kl:	1.495198727	<---- how far we are from the original model (regularizer)

------------------------------ STEP 14 ------------------------------
rewards/mean:	-1.250084877	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.874352574	<---- model-estimated average discounted reward
objective/kl:	0.713339806	<---- how far we are from the original model (regularizer)

------------------------------ STEP 15 ------------------------------
rewards/mean:	-0.278071404	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.797180355	<---- model-estimated average discounted reward
objective/kl:	1.948993683	<---- how far we are from the original model (regularizer)

------------------------------ STEP 16 ------------------------------
rewards/mean:	-0.444755316	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.889322042	<---- model-estimated average discounted reward
objective/kl:	1.505901814	<---- how far we are from the original model (regularizer)

------------------------------ STEP 17 ------------------------------
rewards/mean:	-0.614542961	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.882168353	<---- model-estimated average discounted reward
objective/kl:	1.508326530	<---- how far we are from the original model (regularizer)

------------------------------ STEP 18 ------------------------------
rewards/mean:	-0.682912827	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.902692676	<---- model-estimated average discounted reward
objective/kl:	1.613247395	<---- how far we are from the original model (regularizer)

------------------------------ STEP 19 ------------------------------
rewards/mean:	0.098125458	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.758778811	<---- model-estimated average discounted reward
objective/kl:	2.789164066	<---- how far we are from the original model (regularizer)

------------------------------ STEP 20 ------------------------------
rewards/mean:	-0.619219303	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.839260340	<---- model-estimated average discounted reward
objective/kl:	3.673514366	<---- how far we are from the original model (regularizer)

------------------------------ STEP 21 ------------------------------
rewards/mean:	-0.259645462	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.875951409	<---- model-estimated average discounted reward
objective/kl:	3.480543852	<---- how far we are from the original model (regularizer)

------------------------------ STEP 22 ------------------------------
rewards/mean:	-0.558122635	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.938418031	<---- model-estimated average discounted reward
objective/kl:	2.933200121	<---- how far we are from the original model (regularizer)

------------------------------ STEP 23 ------------------------------
rewards/mean:	-0.139812231	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.828105152	<---- model-estimated average discounted reward
objective/kl:	3.574409962	<---- how far we are from the original model (regularizer)

------------------------------ STEP 24 ------------------------------
rewards/mean:	-0.777312279	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.926609635	<---- model-estimated average discounted reward
objective/kl:	3.449263573	<---- how far we are from the original model (regularizer)

------------------------------ STEP 25 ------------------------------
rewards/mean:	-0.838169098	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.908360064	<---- model-estimated average discounted reward
objective/kl:	3.209358931	<---- how far we are from the original model (regularizer)

------------------------------ STEP 26 ------------------------------
rewards/mean:	-0.529902458	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.922374249	<---- model-estimated average discounted reward
objective/kl:	2.967005730	<---- how far we are from the original model (regularizer)

------------------------------ STEP 27 ------------------------------
rewards/mean:	-0.441819191	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.889926553	<---- model-estimated average discounted reward
objective/kl:	3.153700113	<---- how far we are from the original model (regularizer)

------------------------------ STEP 28 ------------------------------
rewards/mean:	0.131244659	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.774623692	<---- model-estimated average discounted reward
objective/kl:	3.865437031	<---- how far we are from the original model (regularizer)

------------------------------ STEP 29 ------------------------------
rewards/mean:	-0.421091080	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.890693069	<---- model-estimated average discounted reward
objective/kl:	4.284584999	<---- how far we are from the original model (regularizer)

------------------------------ STEP 30 ------------------------------
rewards/mean:	-0.059035301	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.867546618	<---- model-estimated average discounted reward
objective/kl:	3.769965649	<---- how far we are from the original model (regularizer)

------------------------------ STEP 31 ------------------------------
rewards/mean:	-0.019468546	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.879074752	<---- model-estimated average discounted reward
objective/kl:	5.631631851	<---- how far we are from the original model (regularizer)

------------------------------ STEP 32 ------------------------------
rewards/mean:	-0.129155159	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.883649886	<---- model-estimated average discounted reward
objective/kl:	5.082955360	<---- how far we are from the original model (regularizer)

------------------------------ STEP 33 ------------------------------
rewards/mean:	-0.307588577	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.914244473	<---- model-estimated average discounted reward
objective/kl:	5.217827797	<---- how far we are from the original model (regularizer)

------------------------------ STEP 34 ------------------------------
rewards/mean:	0.015220642	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.819020450	<---- model-estimated average discounted reward
objective/kl:	4.824321747	<---- how far we are from the original model (regularizer)

------------------------------ STEP 35 ------------------------------
rewards/mean:	-0.970465660	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.963254094	<---- model-estimated average discounted reward
objective/kl:	4.201615810	<---- how far we are from the original model (regularizer)

------------------------------ STEP 36 ------------------------------
rewards/mean:	-0.161670208	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.858330488	<---- model-estimated average discounted reward
objective/kl:	4.605175972	<---- how far we are from the original model (regularizer)

------------------------------ STEP 37 ------------------------------
rewards/mean:	0.115447044	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.781767666	<---- model-estimated average discounted reward
objective/kl:	3.644989014	<---- how far we are from the original model (regularizer)

------------------------------ STEP 38 ------------------------------
rewards/mean:	0.130042195	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.746931314	<---- model-estimated average discounted reward
objective/kl:	4.566810608	<---- how far we are from the original model (regularizer)

------------------------------ STEP 39 ------------------------------
rewards/mean:	-0.267093658	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.786258757	<---- model-estimated average discounted reward
objective/kl:	3.562619925	<---- how far we are from the original model (regularizer)

------------------------------ STEP 40 ------------------------------
rewards/mean:	-0.074781656	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.714847803	<---- model-estimated average discounted reward
objective/kl:	3.724631786	<---- how far we are from the original model (regularizer)

------------------------------ STEP 41 ------------------------------
rewards/mean:	0.137422323	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.701365590	<---- model-estimated average discounted reward
objective/kl:	3.739686966	<---- how far we are from the original model (regularizer)

------------------------------ STEP 42 ------------------------------
rewards/mean:	0.022407532	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.675400257	<---- model-estimated average discounted reward
objective/kl:	2.372363329	<---- how far we are from the original model (regularizer)

------------------------------ STEP 43 ------------------------------
rewards/mean:	0.100645781	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.608692467	<---- model-estimated average discounted reward
objective/kl:	3.394764185	<---- how far we are from the original model (regularizer)

------------------------------ STEP 44 ------------------------------
rewards/mean:	-0.079744816	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.698448300	<---- model-estimated average discounted reward
objective/kl:	3.937474012	<---- how far we are from the original model (regularizer)

------------------------------ STEP 45 ------------------------------
rewards/mean:	0.005992889	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.611752748	<---- model-estimated average discounted reward
objective/kl:	3.008360386	<---- how far we are from the original model (regularizer)

------------------------------ STEP 46 ------------------------------
rewards/mean:	0.107053757	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.525620222	<---- model-estimated average discounted reward
objective/kl:	3.531836033	<---- how far we are from the original model (regularizer)

------------------------------ STEP 47 ------------------------------
rewards/mean:	0.115253448	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.576041639	<---- model-estimated average discounted reward
objective/kl:	5.026486874	<---- how far we are from the original model (regularizer)

------------------------------ STEP 48 ------------------------------
rewards/mean:	0.226350069	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.518530965	<---- model-estimated average discounted reward
objective/kl:	3.065159082	<---- how far we are from the original model (regularizer)

------------------------------ STEP 49 ------------------------------
rewards/mean:	0.367893219	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.447247386	<---- model-estimated average discounted reward
objective/kl:	4.449466228	<---- how far we are from the original model (regularizer)

------------------------------ STEP 50 ------------------------------
rewards/mean:	0.077795029	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.427044272	<---- model-estimated average discounted reward
objective/kl:	4.438166618	<---- how far we are from the original model (regularizer)

------------------------------ STEP 51 ------------------------------
rewards/mean:	0.578823090	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.357383132	<---- model-estimated average discounted reward
objective/kl:	5.274995804	<---- how far we are from the original model (regularizer)

------------------------------ STEP 52 ------------------------------
rewards/mean:	0.328418732	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.400156558	<---- model-estimated average discounted reward
objective/kl:	6.143702507	<---- how far we are from the original model (regularizer)

------------------------------ STEP 53 ------------------------------
rewards/mean:	0.429744363	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.344648361	<---- model-estimated average discounted reward
objective/kl:	6.794788361	<---- how far we are from the original model (regularizer)

------------------------------ STEP 54 ------------------------------
rewards/mean:	0.263243675	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.341956884	<---- model-estimated average discounted reward
objective/kl:	5.780643463	<---- how far we are from the original model (regularizer)

------------------------------ STEP 55 ------------------------------
rewards/mean:	0.819453716	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.305271626	<---- model-estimated average discounted reward
objective/kl:	5.976068974	<---- how far we are from the original model (regularizer)

------------------------------ STEP 56 ------------------------------
rewards/mean:	1.202861786	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.184535801	<---- model-estimated average discounted reward
objective/kl:	6.594683647	<---- how far we are from the original model (regularizer)

------------------------------ STEP 57 ------------------------------
rewards/mean:	0.680335045	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.230088860	<---- model-estimated average discounted reward
objective/kl:	6.629478455	<---- how far we are from the original model (regularizer)

------------------------------ STEP 58 ------------------------------
rewards/mean:	0.557498932	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.211315289	<---- model-estimated average discounted reward
objective/kl:	6.851882458	<---- how far we are from the original model (regularizer)

------------------------------ STEP 59 ------------------------------
rewards/mean:	0.243222237	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.242073298	<---- model-estimated average discounted reward
objective/kl:	5.442400932	<---- how far we are from the original model (regularizer)

------------------------------ STEP 60 ------------------------------
rewards/mean:	0.654839516	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.185514167	<---- model-estimated average discounted reward
objective/kl:	5.790283203	<---- how far we are from the original model (regularizer)

------------------------------ STEP 61 ------------------------------
rewards/mean:	0.633575439	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	-0.140423164	<---- model-estimated average discounted reward
objective/kl:	6.172468185	<---- how far we are from the original model (regularizer)


In [ ]:
model = ppo_trainer.model.pretrained_model

In [ ]:
# <YOUR CODE HERE> - feel free to organize it as you see fit
# <YOUR CODE HERE> - feel free to organize it as you see fit
def sample_positive(prompt, n_samples=16, print_all_samples=True):
    """Generate n_samples samples and choose the best ranked one by reward_model"""
    inputs = main_tokenizer([prompt] * n_samples, return_tensors='pt').to(device)

    with torch.no_grad():
        candidates = model.generate(**inputs, max_new_tokens=50, do_sample=True)

    samples=[]
    print("="*50)
    for candidate in candidates:
        sample = main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist(), skip_special_tokens=True)

        samples.append(sample)

        if print_all_samples:
            print(f"Sample: {sample}")

    with torch.no_grad():
        out = reward_model(**reward_tokenizer(samples, padding="max_length", truncation=True, max_length=512, return_tensors="pt").to(device))
    best_id = torch.argmax(out.logits[:, 0])

    print(f"BEST: {samples[best_id]}")
    print("="*50)

prompts = ["She was a", "I hope you", "It was the last", "From the beginning", "This experience"]

for prompt in prompts:
    sample_positive(prompt)
    print()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: She was a lovely actress with beautiful beauty, but she was not perfect. Not enough to make me laugh.
Sample: She was a very interesting human being with the talent, but he was so incredibly, not unlike, "Eddie" by George C. Scott on the other hand, was very, very good. He is very hard to believe that it was he who played
Sample: She was a pretty good-looking girl. The kids liked the girls and her dad was a real good-looking family. A poor girl (played nicely by another girl)... was in a crappy marriage, not a big girl... but a decent-looking woman
Sample: She was a really good looking, even if everyone else looked bad to her. I really liked John Travolta.<br /><br />And, of course, she had a really good little little boy, who looked so different in the early years of
Sample: She was a good dancer and that role is very well done. I've seen the short film before but it's really amazing. The movie starts out to be a very emotional part of the movie. There is a great fight with the girl. The two really do
Sample: She was a real bad girl. I think she would have fallen in love with something.<br /><br />And for what I felt she should have died in the end because the guy just ran out of money. Anyway, she did fall for him and fell
Sample: She was a good friend of hers." - David T. Williams, "A Beautiful Mind" (1933). <br /><br />The movie features a number of young people, who are mostly the same as when George was growing up in Brooklyn.<br
Sample: She was a beautiful actress of the era, had a beautiful, gorgeous heart, and had a pretty face. No one could pass this off as an innocent mistake, and that would have been a very tragic mistake. This is the first of a series of films that
Sample: She was a very good film, even though nothing you see is true. What made she a great film was the beautiful woman in one of her roles. I am a good guy and can understand that. She had a big part to lose in the film, but
Sample: She was a brilliant actor - and this role was very much an action hero. This movie had a big budget but it was not on my schedule - so I don't think I want another one. I don't like to say how many of these I am talking
Sample: She was a genius, as well as one of the very good (and talented) players. She is a wonderful person with such an incredible amount of talent. After all, why would she want to take over the world? She's a beautiful girl who just wanted
Sample: She was a really good actress. I like those things where it gets all the way to the end. She has a sweet, beautiful, and tragic sense of humor. She's the type of person who plays down to nothing with a knife. And you get to
Sample: She was a bad actor, because he must have looked as if he were trying to do the type of character he was trying to do; he was an actor and he was a great actor in an all-around movie. How can you expect to make a movie
Sample: She was a great artist, she was a great film maker, she was all kind, but she didn't have the same passion, the movie lacked the same quality as the movies of yesteryear, and it had the same feel. the main thing that really
Sample: She was a good, great lady. We were happy. Then we got to the "p" in a very bad way. It was all right with a couple of little things, but it is not over.<br /><br />The "p" is
Sample: She was a great actress and a good-hearted person, I love what she's wearing, and I respect a lot her personal qualities, but in this one she is a little bit of a freak with the reality of what it takes to be a woman. Her
BEST: She was a pretty good-looking girl. The kids liked the girls and her dad was a real good-looking family. A poor girl (played nicely by another girl)... was in a crappy marriage, not a big girl... but a decent-looking woman
==================================================

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: I hope you will watch her because they have more than their share of the fun." (As she and her husband are not in the same room ) The film ends with one of the great comedies of the 50s, "Gimme Shelter", which had
Sample: I hope you get a lot of credit for this. Let me say this is not a movie for all films. I think its just another attempt to show the depths of cinema. The story focuses on a woman with one girl (anonymous.) (A woman like
Sample: I hope you will make a real movie with me. It is a movie I've been in about 3 days and thought a lot. I didn't believe the first one was so good, and really good, in a real way. I think I have it right
Sample: I hope you won't read "Titanic". I'm going to tell you something very important.<br /><br />Yes, we are going to see a very strange place. I'll say what we do...and that's that we're going to
Sample: I hope you never buy this film. Once its in, you will have a new experience in the cinema. You will be a movie addict to the point of you will appreciate, to the point you will probably see a movie by someone in your class. If you
Sample: I hope you all get lost in your own words and see it.<br /><br />That is a sad and very sad statement. I cannot believe that my wife and daughter did not know this, and to be honest, I don't blame them either.<
Sample: I hope you're too.." But "I don't want my family to die and if they can't be allowed to take my children away from me, and just me, then it's my family". I hope you don't try to change the world,
Sample: I hope you and your family will not only know that there is no God as depicted in the movie but also know that at your parents' wedding you will get the opportunity to feel as if you have to be on earth as a prophet. God will make you aware
Sample: I hope you all have a great time in their holiday time....<br /><br />Also please note, that after this is posted to "the internet", you are in the wrong place...<br /><br />I guess you could give it 10
Sample: I hope you all that a) the "bad guy" is a good guy, b) his wife is a psychopath, c) he's a drug-addicted "daddy" and c) the kid is a fat moron. If you are in
Sample: I hope you'll do well!
Sample: I hope you have an orgasm. You have the best sex in the world.
Sample: I hope you can't do a "Sleeping Son" film that was so funny and thought provoking. I don't want myself to believe someone can make these things to people who don't know the original.
Sample: I hope you are watching something that shows a good and well made film so that those watching it also can still have some peace and some horror. If you think it is a horror you're absolutely wrong. No one else can see it and have a good experience.
Sample: I hope you get that too. I think I have been in a situation like this where I have found myself in the most difficult situation imaginable. I have found myself having so much trouble with so many different things. It is my belief that if I choose to live
Sample: I hope you don't see the world's biggest film. You might be wondering, "Does anyone else hear that?" Well, I don't think there is any doubt about that. All I can say is that what people don't know, and don't want
BEST: I hope you all that a) the "bad guy" is a good guy, b) his wife is a psychopath, c) he's a drug-addicted "daddy" and c) the kid is a fat moron. If you are in
==================================================

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: It was the last film to hit the big screen. That's an interesting statement that you just get right by going in the wrong direction. The title of the film is so misleading that its been used many times. You see, the films are trying to move us and
Sample: It was the last time I watched this film.<br /><br />I'd wager the same of you might see it today because so many other films have tried to do the same. But just because you don't know any of the new ones does not make
Sample: It was the last moment of the film in the history of "Silence from the Screen". If it were not for Richard Gere and his lovely female counterpart, the film would have survived any chance. Instead they gave him a wonderful, but completely unnecessary, sex machine
Sample: It was the last few seconds before the 'Mulan' 'WTF?' movie I remembered. And, to add to the shock factor, the movie's cover design and other "bizarre" scenes, which are used as clues or clues to the plot
Sample: It was the last nail in the coffin of the greatest actor so far that may just be the last film of the decade but in this respect you all know what you have! For once in your life you'll go to your grave! For once in your life, I
Sample: It was the last movie in my life I liked. When I finished the movie I thought my family would be surprised by this movie I would not be too worried about what happened next .<br /><br />A lot of people who have seen this movie have been
Sample: It was the last time I would go out to see the movie.<br /><br />"Goblins" is the perfect movie to watch in case of a major disaster. The film is based on an old story about an old man's wife and her son
Sample: It was the last show of the year and really felt like it - so it made me cry with the way that their last year was structured. Not the good thing if you put us all at risk. It was all just bad, in a different kind of way (
Sample: It was the last time he played a bad old school football coach, but he's still the best! And he was the first guy to do the job so I thought this could be the end of him, or a good little kid who'd do the whole thing.
Sample: It was the last film I saw before the war. I did it for a living. It was a war film, a comedy film, a suspense film, a drama film, a drama film, a drama film.<br /><br />I was an old-
Sample: It was the last episode on TBS, and it's been one of the great thing of the past 10 years. The rest of the cast is terrific. It is my opinion that the main problems were never solved, but that the show got out of hand for the
Sample: It was the last of this movie that would make me cry. I don't think it deserved the $13.8 million that it was, but who got to blame it on. The bad guy had to come in at the right time, to make him all the
Sample: It was the last of the two films, on which the story was more of a story, rather than a story. If the plot wasn't going well it was not that great to say about this. Maybe it was an excuse for a new start and all the characters
Sample: It was the last and I can't remember what kind. The second film was a lot more interesting than the third. It was really like a love story. I was told how they made this love story because every week we see them grow. We know they're only
Sample: It was the last shot of the rest of the film, and I really should tell you that, because they would have had it just over three minutes ahead of the movie. But I have no idea who will get paid to write the story. It was probably their own
Sample: It was the last time I'd watch this film. My best friends would have loved it. My "bad" friend would have loved it. I think this time I'm going to give it a 2.
BEST: It was the last time he played a bad old school football coach, but he's still the best! And he was the first guy to do the job so I thought this could be the end of him, or a good little kid who'd do the whole thing.
==================================================

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

==================================================
Sample: From the beginning, there are two different endings, however they are based on a great combination of the characters, the two antagonists and our hero, together form a great series. The best part of the series is the very funny and amazing comedy in the first, as
Sample: From the beginning) the title is nothing. The character is actually a dog or something. The whole point of the film is to drive the cat away from the point of a police dog. The way this goes, he isn't a bad guy, but not a
Sample: From the beginning to last scene the film, there is no surprise.<br /><br />The story is what it's all about. If there was any way to see it, it is the film. If there were any way to see it, it would
Sample: From the beginning he was played by Arthur Lee Smith).The film starts up with him, and the girl (Olivia Harnes) and her brother (Gus Moroder) is falling into the heart of a world that hates people.<br /><
Sample: From the beginning, this is the best film ever in my opinion - as the great American film "The Passion" proves - it doesn't have the same quality. That it's "the American Way" isn't really the fault of IMDb, or it's
Sample: From the beginning, there are a lot of beautiful, great, and complex scenes in the movie that go back to the days where the original TV show was created. The movie ends with the "great" and "great" scenes with the great scenes being destroyed,
Sample: From the beginning the first time I saw that "Kitsawagi" was so overused, then it got a lot more serious but it remains the same thing - a silly and pointless action flick about women fighting. However when it's not just the action,
Sample: From the beginning, the only thing stopping them from fighting is a girl named Sae. While she is still a friend, her parents are out to get Sae and her mother, who is also very good and a good guy.<br /><br />In
Sample: From the beginning of the movie we are shown a small, small, small-scale city where the police are led by the lead character of a young woman who is trapped in a dark dungeon filled with evil things. When she arrives in their city she doesn't realise
Sample: From the beginning of a war on his homeland the Germans had given every single member of the enemy a piece of meat. They had made him a giant kangaroo, stuffed it in his belly like it belonged to a young girl, and put it in his mouth
Sample: From the beginning of the film he is looking at a very handsome looking man. He looks like a very handsome man.<br /><br />As you can see the man looks the "beautiful" as the man. He is very appealing. He is also
Sample: From the beginning, after the death of M&M's lead guy, the film is a good one. The cinematography and music, and most of the shots that are in that final, is superb. I couldn't get back to my seat or my seats
Sample: From the beginning of the film you see: the camera rolling over, and the characters just hanging in the air. Of those characters, you almost feel like you're watching them. Of those characters, you're in the right places. There are people who you're
Sample: From the beginning of this episode in the very early tomid 1960's, it is obvious that John Carradine(JW) is attempting to move in the right direction with these four actors of his. The fact that he hasn't quite made it seems to
Sample: From the beginning to the end). What the filmmakers have done is leave us wondering what was going through our heads. If you don't understand that, or think it's a good show about two high school grad, what's the point? The film is like the
Sample: From the beginning of this movie it was as if an old man with the ability to create a wall was watching it, and having the ability. All in all, it is a comedy of violence, sex, revenge, and romance. Yes it's pretty cool to
BEST: From the beginning of a war on his homeland the Germans had given every single member of the enemy a piece of meat. They had made him a giant kangaroo, stuffed it in his belly like it belonged to a young girl, and put it in his mouth
==================================================

==================================================
Sample: This experience is the first of two or three from this show to be made into something very, very special. I will have no problem just taking the show off now without any additional charges and without the special effects either.<br /><br />Cinema
Sample: This experience is very funny, but there is nothing particularly memorable. You get a good idea of what a typical young movie is about. <br /><br />The movie is the opposite of the one after it was put back together by the title characters in
Sample: This experience is where much of the humor comes from the characters. The story is not too bad of a story, and the pacing is good but the character's are an extremely weak character. There is little redeeming the series of stories that were supposed to be
Sample: This experience might have been less effective if they were trying to make it out from a film. After the movie, the film would have been pretty bland. The first time we were given a true story, the story went downhill, because we had seen a lot
Sample: This experience will show our characters and their choices at the end, that they made the decision to become the next victims of police brutality... This is an amazing, disturbing look into our police culture.<br /><br />Watched once before on HBO, it
Sample: This experience to me was full of pain. I know because in my old age, I was very, very angry I was at the things I went through, the stuff I saw and the things I hate, I can relate to that. But I don't
Sample: This experience left me very much in love with the characters, even for my own brother. That was the main reason why this documentary ended in such a sad ending. If you are an avid viewer of movies like I would love to go see this movie. I
Sample: This experience is a wonderful example of the same kind, but for the reasons that he is writing, as part of it, he is not one of a hundred people who are willing to give in if they want to believe that the truth has been revealed to them
Sample: This experience gave it an edge and gave me something to work with. For example, we had an experience with a family who lived in a poor, dirt-filled city and the family made a film for a film festival. It was a big success on the
Sample: This experience was one of the greatest movies I've ever seen. It gave me a chance to experience a much more intelligent than the first movie. I had an incredibly soft spot in my own heart for a movie about a man with an ex-wife in his
Sample: This experience was a disappointment, but a good one. Although, some bad stuff in the movie was interesting, but the movie was boring. I wish that they had just added some more of the bad parts and added some more fun for the movie. I was
Sample: This experience is a fascinating view of two very different worlds, the good and bad, love from the devil and the good in general. For one: the devil, the good; and the bad. Both seem very strange and very different; they both seem very
Sample: This experience will take a lot for you to overcome. The main characters are quite similar, and this film is just an adventure. Just enjoy the action and the story is so simple... it is worth watching for just that and the music. The plot is very
Sample: This experience is that the actors, cinematographer and scriptwriter are trying to reach the audience who already know what is going on, with no knowledge that it is going on." It's a movie in which it is very obvious, on first sight, that
Sample: This experience is beyond our comprehension. It does not follow the same pattern. It is unlike the "A-to-be" as a movie. I was thinking that it was very hard to see so many people that would appear in and be associated with "
Sample: This experience does not explain the existence of the man (Bobby) who had this happen on one night, without any reason or reason at all. The plot is that Bobby who looks upon his daughter and her mother as a "mummy" and thus we
BEST: This experience gave it an edge and gave me something to work with. For example, we had an experience with a family who lived in a poor, dirt-filled city and the family made a film for a film festival. It was a big success on the
==================================================

Perhaps filtering comments (leaving most obscene/insulting ones) would give more visible results. Idea 1: leave couple of toxic categories, not all of them.
Idea 2: use model that was finetuned for classifying comments (toxic/non_toxic) and use this model outputs to filter out the dataset.